// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: map.proto

#ifndef PROTOBUF_INCLUDED_map_2eproto
#define PROTOBUF_INCLUDED_map_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "map_clear_area.pb.h"
#include "map_crosswalk.pb.h"
#include "map_junction.pb.h"
#include "map_lane.pb.h"
#include "map_overlap.pb.h"
#include "map_signal.pb.h"
#include "map_speed_bump.pb.h"
#include "map_stop_sign.pb.h"
#include "map_yield_sign.pb.h"
#include "map_road.pb.h"
#include "map_parking_space.pb.h"
#include "map_pnc_junction.pb.h"
#include "map_rsu.pb.h"
#include "map_c5_area.pb.h"
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_map_2eproto 

namespace protobuf_map_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[3];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_map_2eproto
namespace cvte {
namespace hdmap {
class Header;
class HeaderDefaultTypeInternal;
extern HeaderDefaultTypeInternal _Header_default_instance_;
class Map;
class MapDefaultTypeInternal;
extern MapDefaultTypeInternal _Map_default_instance_;
class Projection;
class ProjectionDefaultTypeInternal;
extern ProjectionDefaultTypeInternal _Projection_default_instance_;
}  // namespace hdmap
}  // namespace cvte
namespace google {
namespace protobuf {
template<> ::cvte::hdmap::Header* Arena::CreateMaybeMessage<::cvte::hdmap::Header>(Arena*);
template<> ::cvte::hdmap::Map* Arena::CreateMaybeMessage<::cvte::hdmap::Map>(Arena*);
template<> ::cvte::hdmap::Projection* Arena::CreateMaybeMessage<::cvte::hdmap::Projection>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace cvte {
namespace hdmap {

// ===================================================================

class Projection : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:cvte.hdmap.Projection) */ {
 public:
  Projection();
  virtual ~Projection();

  Projection(const Projection& from);

  inline Projection& operator=(const Projection& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Projection(Projection&& from) noexcept
    : Projection() {
    *this = ::std::move(from);
  }

  inline Projection& operator=(Projection&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Projection& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Projection* internal_default_instance() {
    return reinterpret_cast<const Projection*>(
               &_Projection_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(Projection* other);
  friend void swap(Projection& a, Projection& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Projection* New() const final {
    return CreateMaybeMessage<Projection>(NULL);
  }

  Projection* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Projection>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Projection& from);
  void MergeFrom(const Projection& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Projection* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string proj = 1;
  bool has_proj() const;
  void clear_proj();
  static const int kProjFieldNumber = 1;
  const ::std::string& proj() const;
  void set_proj(const ::std::string& value);
  #if LANG_CXX11
  void set_proj(::std::string&& value);
  #endif
  void set_proj(const char* value);
  void set_proj(const char* value, size_t size);
  ::std::string* mutable_proj();
  ::std::string* release_proj();
  void set_allocated_proj(::std::string* proj);

  // @@protoc_insertion_point(class_scope:cvte.hdmap.Projection)
 private:
  void set_has_proj();
  void clear_has_proj();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr proj_;
  friend struct ::protobuf_map_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Header : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:cvte.hdmap.Header) */ {
 public:
  Header();
  virtual ~Header();

  Header(const Header& from);

  inline Header& operator=(const Header& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Header(Header&& from) noexcept
    : Header() {
    *this = ::std::move(from);
  }

  inline Header& operator=(Header&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Header& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Header* internal_default_instance() {
    return reinterpret_cast<const Header*>(
               &_Header_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(Header* other);
  friend void swap(Header& a, Header& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Header* New() const final {
    return CreateMaybeMessage<Header>(NULL);
  }

  Header* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Header>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Header& from);
  void MergeFrom(const Header& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Header* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional bytes version = 1;
  bool has_version() const;
  void clear_version();
  static const int kVersionFieldNumber = 1;
  const ::std::string& version() const;
  void set_version(const ::std::string& value);
  #if LANG_CXX11
  void set_version(::std::string&& value);
  #endif
  void set_version(const char* value);
  void set_version(const void* value, size_t size);
  ::std::string* mutable_version();
  ::std::string* release_version();
  void set_allocated_version(::std::string* version);

  // optional bytes date = 2;
  bool has_date() const;
  void clear_date();
  static const int kDateFieldNumber = 2;
  const ::std::string& date() const;
  void set_date(const ::std::string& value);
  #if LANG_CXX11
  void set_date(::std::string&& value);
  #endif
  void set_date(const char* value);
  void set_date(const void* value, size_t size);
  ::std::string* mutable_date();
  ::std::string* release_date();
  void set_allocated_date(::std::string* date);

  // optional bytes district = 4;
  bool has_district() const;
  void clear_district();
  static const int kDistrictFieldNumber = 4;
  const ::std::string& district() const;
  void set_district(const ::std::string& value);
  #if LANG_CXX11
  void set_district(::std::string&& value);
  #endif
  void set_district(const char* value);
  void set_district(const void* value, size_t size);
  ::std::string* mutable_district();
  ::std::string* release_district();
  void set_allocated_district(::std::string* district);

  // optional bytes generation = 5;
  bool has_generation() const;
  void clear_generation();
  static const int kGenerationFieldNumber = 5;
  const ::std::string& generation() const;
  void set_generation(const ::std::string& value);
  #if LANG_CXX11
  void set_generation(::std::string&& value);
  #endif
  void set_generation(const char* value);
  void set_generation(const void* value, size_t size);
  ::std::string* mutable_generation();
  ::std::string* release_generation();
  void set_allocated_generation(::std::string* generation);

  // optional bytes rev_major = 6;
  bool has_rev_major() const;
  void clear_rev_major();
  static const int kRevMajorFieldNumber = 6;
  const ::std::string& rev_major() const;
  void set_rev_major(const ::std::string& value);
  #if LANG_CXX11
  void set_rev_major(::std::string&& value);
  #endif
  void set_rev_major(const char* value);
  void set_rev_major(const void* value, size_t size);
  ::std::string* mutable_rev_major();
  ::std::string* release_rev_major();
  void set_allocated_rev_major(::std::string* rev_major);

  // optional bytes rev_minor = 7;
  bool has_rev_minor() const;
  void clear_rev_minor();
  static const int kRevMinorFieldNumber = 7;
  const ::std::string& rev_minor() const;
  void set_rev_minor(const ::std::string& value);
  #if LANG_CXX11
  void set_rev_minor(::std::string&& value);
  #endif
  void set_rev_minor(const char* value);
  void set_rev_minor(const void* value, size_t size);
  ::std::string* mutable_rev_minor();
  ::std::string* release_rev_minor();
  void set_allocated_rev_minor(::std::string* rev_minor);

  // optional bytes vendor = 12;
  bool has_vendor() const;
  void clear_vendor();
  static const int kVendorFieldNumber = 12;
  const ::std::string& vendor() const;
  void set_vendor(const ::std::string& value);
  #if LANG_CXX11
  void set_vendor(::std::string&& value);
  #endif
  void set_vendor(const char* value);
  void set_vendor(const void* value, size_t size);
  ::std::string* mutable_vendor();
  ::std::string* release_vendor();
  void set_allocated_vendor(::std::string* vendor);

  // optional .cvte.hdmap.Projection projection = 3;
  bool has_projection() const;
  void clear_projection();
  static const int kProjectionFieldNumber = 3;
  private:
  const ::cvte::hdmap::Projection& _internal_projection() const;
  public:
  const ::cvte::hdmap::Projection& projection() const;
  ::cvte::hdmap::Projection* release_projection();
  ::cvte::hdmap::Projection* mutable_projection();
  void set_allocated_projection(::cvte::hdmap::Projection* projection);

  // optional double left = 8;
  bool has_left() const;
  void clear_left();
  static const int kLeftFieldNumber = 8;
  double left() const;
  void set_left(double value);

  // optional double top = 9;
  bool has_top() const;
  void clear_top();
  static const int kTopFieldNumber = 9;
  double top() const;
  void set_top(double value);

  // optional double right = 10;
  bool has_right() const;
  void clear_right();
  static const int kRightFieldNumber = 10;
  double right() const;
  void set_right(double value);

  // optional double bottom = 11;
  bool has_bottom() const;
  void clear_bottom();
  static const int kBottomFieldNumber = 11;
  double bottom() const;
  void set_bottom(double value);

  // @@protoc_insertion_point(class_scope:cvte.hdmap.Header)
 private:
  void set_has_version();
  void clear_has_version();
  void set_has_date();
  void clear_has_date();
  void set_has_projection();
  void clear_has_projection();
  void set_has_district();
  void clear_has_district();
  void set_has_generation();
  void clear_has_generation();
  void set_has_rev_major();
  void clear_has_rev_major();
  void set_has_rev_minor();
  void clear_has_rev_minor();
  void set_has_left();
  void clear_has_left();
  void set_has_top();
  void clear_has_top();
  void set_has_right();
  void clear_has_right();
  void set_has_bottom();
  void clear_has_bottom();
  void set_has_vendor();
  void clear_has_vendor();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr version_;
  ::google::protobuf::internal::ArenaStringPtr date_;
  ::google::protobuf::internal::ArenaStringPtr district_;
  ::google::protobuf::internal::ArenaStringPtr generation_;
  ::google::protobuf::internal::ArenaStringPtr rev_major_;
  ::google::protobuf::internal::ArenaStringPtr rev_minor_;
  ::google::protobuf::internal::ArenaStringPtr vendor_;
  ::cvte::hdmap::Projection* projection_;
  double left_;
  double top_;
  double right_;
  double bottom_;
  friend struct ::protobuf_map_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Map : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:cvte.hdmap.Map) */ {
 public:
  Map();
  virtual ~Map();

  Map(const Map& from);

  inline Map& operator=(const Map& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Map(Map&& from) noexcept
    : Map() {
    *this = ::std::move(from);
  }

  inline Map& operator=(Map&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Map& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Map* internal_default_instance() {
    return reinterpret_cast<const Map*>(
               &_Map_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(Map* other);
  friend void swap(Map& a, Map& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Map* New() const final {
    return CreateMaybeMessage<Map>(NULL);
  }

  Map* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Map>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Map& from);
  void MergeFrom(const Map& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Map* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .cvte.hdmap.Crosswalk crosswalk = 2;
  int crosswalk_size() const;
  void clear_crosswalk();
  static const int kCrosswalkFieldNumber = 2;
  ::cvte::hdmap::Crosswalk* mutable_crosswalk(int index);
  ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::Crosswalk >*
      mutable_crosswalk();
  const ::cvte::hdmap::Crosswalk& crosswalk(int index) const;
  ::cvte::hdmap::Crosswalk* add_crosswalk();
  const ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::Crosswalk >&
      crosswalk() const;

  // repeated .cvte.hdmap.Junction junction = 3;
  int junction_size() const;
  void clear_junction();
  static const int kJunctionFieldNumber = 3;
  ::cvte::hdmap::Junction* mutable_junction(int index);
  ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::Junction >*
      mutable_junction();
  const ::cvte::hdmap::Junction& junction(int index) const;
  ::cvte::hdmap::Junction* add_junction();
  const ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::Junction >&
      junction() const;

  // repeated .cvte.hdmap.Lane lane = 4;
  int lane_size() const;
  void clear_lane();
  static const int kLaneFieldNumber = 4;
  ::cvte::hdmap::Lane* mutable_lane(int index);
  ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::Lane >*
      mutable_lane();
  const ::cvte::hdmap::Lane& lane(int index) const;
  ::cvte::hdmap::Lane* add_lane();
  const ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::Lane >&
      lane() const;

  // repeated .cvte.hdmap.StopSign stop_sign = 5;
  int stop_sign_size() const;
  void clear_stop_sign();
  static const int kStopSignFieldNumber = 5;
  ::cvte::hdmap::StopSign* mutable_stop_sign(int index);
  ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::StopSign >*
      mutable_stop_sign();
  const ::cvte::hdmap::StopSign& stop_sign(int index) const;
  ::cvte::hdmap::StopSign* add_stop_sign();
  const ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::StopSign >&
      stop_sign() const;

  // repeated .cvte.hdmap.Signal signal = 6;
  int signal_size() const;
  void clear_signal();
  static const int kSignalFieldNumber = 6;
  ::cvte::hdmap::Signal* mutable_signal(int index);
  ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::Signal >*
      mutable_signal();
  const ::cvte::hdmap::Signal& signal(int index) const;
  ::cvte::hdmap::Signal* add_signal();
  const ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::Signal >&
      signal() const;

  // repeated .cvte.hdmap.YieldSign yield = 7;
  int yield_size() const;
  void clear_yield();
  static const int kYieldFieldNumber = 7;
  ::cvte::hdmap::YieldSign* mutable_yield(int index);
  ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::YieldSign >*
      mutable_yield();
  const ::cvte::hdmap::YieldSign& yield(int index) const;
  ::cvte::hdmap::YieldSign* add_yield();
  const ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::YieldSign >&
      yield() const;

  // repeated .cvte.hdmap.Overlap overlap = 8;
  int overlap_size() const;
  void clear_overlap();
  static const int kOverlapFieldNumber = 8;
  ::cvte::hdmap::Overlap* mutable_overlap(int index);
  ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::Overlap >*
      mutable_overlap();
  const ::cvte::hdmap::Overlap& overlap(int index) const;
  ::cvte::hdmap::Overlap* add_overlap();
  const ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::Overlap >&
      overlap() const;

  // repeated .cvte.hdmap.ClearArea clear_area = 9;
  int clear_area_size() const;
  void clear_clear_area();
  static const int kClearAreaFieldNumber = 9;
  ::cvte::hdmap::ClearArea* mutable_clear_area(int index);
  ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::ClearArea >*
      mutable_clear_area();
  const ::cvte::hdmap::ClearArea& clear_area(int index) const;
  ::cvte::hdmap::ClearArea* add_clear_area();
  const ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::ClearArea >&
      clear_area() const;

  // repeated .cvte.hdmap.SpeedBump speed_bump = 10;
  int speed_bump_size() const;
  void clear_speed_bump();
  static const int kSpeedBumpFieldNumber = 10;
  ::cvte::hdmap::SpeedBump* mutable_speed_bump(int index);
  ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::SpeedBump >*
      mutable_speed_bump();
  const ::cvte::hdmap::SpeedBump& speed_bump(int index) const;
  ::cvte::hdmap::SpeedBump* add_speed_bump();
  const ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::SpeedBump >&
      speed_bump() const;

  // repeated .cvte.hdmap.Road road = 11;
  int road_size() const;
  void clear_road();
  static const int kRoadFieldNumber = 11;
  ::cvte::hdmap::Road* mutable_road(int index);
  ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::Road >*
      mutable_road();
  const ::cvte::hdmap::Road& road(int index) const;
  ::cvte::hdmap::Road* add_road();
  const ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::Road >&
      road() const;

  // repeated .cvte.hdmap.ParkingSpace parking_space = 12;
  int parking_space_size() const;
  void clear_parking_space();
  static const int kParkingSpaceFieldNumber = 12;
  ::cvte::hdmap::ParkingSpace* mutable_parking_space(int index);
  ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::ParkingSpace >*
      mutable_parking_space();
  const ::cvte::hdmap::ParkingSpace& parking_space(int index) const;
  ::cvte::hdmap::ParkingSpace* add_parking_space();
  const ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::ParkingSpace >&
      parking_space() const;

  // repeated .cvte.hdmap.PNCJunction pnc_junction = 13;
  int pnc_junction_size() const;
  void clear_pnc_junction();
  static const int kPncJunctionFieldNumber = 13;
  ::cvte::hdmap::PNCJunction* mutable_pnc_junction(int index);
  ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::PNCJunction >*
      mutable_pnc_junction();
  const ::cvte::hdmap::PNCJunction& pnc_junction(int index) const;
  ::cvte::hdmap::PNCJunction* add_pnc_junction();
  const ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::PNCJunction >&
      pnc_junction() const;

  // repeated .cvte.hdmap.RSU rsu = 14;
  int rsu_size() const;
  void clear_rsu();
  static const int kRsuFieldNumber = 14;
  ::cvte::hdmap::RSU* mutable_rsu(int index);
  ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::RSU >*
      mutable_rsu();
  const ::cvte::hdmap::RSU& rsu(int index) const;
  ::cvte::hdmap::RSU* add_rsu();
  const ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::RSU >&
      rsu() const;

  // repeated .cvte.hdmap.MapArea map_area = 15;
  int map_area_size() const;
  void clear_map_area();
  static const int kMapAreaFieldNumber = 15;
  ::cvte::hdmap::MapArea* mutable_map_area(int index);
  ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::MapArea >*
      mutable_map_area();
  const ::cvte::hdmap::MapArea& map_area(int index) const;
  ::cvte::hdmap::MapArea* add_map_area();
  const ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::MapArea >&
      map_area() const;

  // repeated .cvte.hdmap.CleanArea clean_area = 16;
  int clean_area_size() const;
  void clear_clean_area();
  static const int kCleanAreaFieldNumber = 16;
  ::cvte::hdmap::CleanArea* mutable_clean_area(int index);
  ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::CleanArea >*
      mutable_clean_area();
  const ::cvte::hdmap::CleanArea& clean_area(int index) const;
  ::cvte::hdmap::CleanArea* add_clean_area();
  const ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::CleanArea >&
      clean_area() const;

  // repeated .cvte.hdmap.SlopeArea slope_area = 17;
  int slope_area_size() const;
  void clear_slope_area();
  static const int kSlopeAreaFieldNumber = 17;
  ::cvte::hdmap::SlopeArea* mutable_slope_area(int index);
  ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::SlopeArea >*
      mutable_slope_area();
  const ::cvte::hdmap::SlopeArea& slope_area(int index) const;
  ::cvte::hdmap::SlopeArea* add_slope_area();
  const ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::SlopeArea >&
      slope_area() const;

  // repeated .cvte.hdmap.Elevator elevator = 18;
  int elevator_size() const;
  void clear_elevator();
  static const int kElevatorFieldNumber = 18;
  ::cvte::hdmap::Elevator* mutable_elevator(int index);
  ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::Elevator >*
      mutable_elevator();
  const ::cvte::hdmap::Elevator& elevator(int index) const;
  ::cvte::hdmap::Elevator* add_elevator();
  const ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::Elevator >&
      elevator() const;

  // repeated .cvte.hdmap.NarrowArea narrow_area = 19;
  int narrow_area_size() const;
  void clear_narrow_area();
  static const int kNarrowAreaFieldNumber = 19;
  ::cvte::hdmap::NarrowArea* mutable_narrow_area(int index);
  ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::NarrowArea >*
      mutable_narrow_area();
  const ::cvte::hdmap::NarrowArea& narrow_area(int index) const;
  ::cvte::hdmap::NarrowArea* add_narrow_area();
  const ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::NarrowArea >&
      narrow_area() const;

  // repeated .cvte.hdmap.MarkArea mark_area = 20;
  int mark_area_size() const;
  void clear_mark_area();
  static const int kMarkAreaFieldNumber = 20;
  ::cvte::hdmap::MarkArea* mutable_mark_area(int index);
  ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::MarkArea >*
      mutable_mark_area();
  const ::cvte::hdmap::MarkArea& mark_area(int index) const;
  ::cvte::hdmap::MarkArea* add_mark_area();
  const ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::MarkArea >&
      mark_area() const;

  // repeated .cvte.hdmap.ProhibitedArea prohibited_area = 21;
  int prohibited_area_size() const;
  void clear_prohibited_area();
  static const int kProhibitedAreaFieldNumber = 21;
  ::cvte::hdmap::ProhibitedArea* mutable_prohibited_area(int index);
  ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::ProhibitedArea >*
      mutable_prohibited_area();
  const ::cvte::hdmap::ProhibitedArea& prohibited_area(int index) const;
  ::cvte::hdmap::ProhibitedArea* add_prohibited_area();
  const ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::ProhibitedArea >&
      prohibited_area() const;

  // repeated .cvte.hdmap.BlackArea black_area = 22;
  int black_area_size() const;
  void clear_black_area();
  static const int kBlackAreaFieldNumber = 22;
  ::cvte::hdmap::BlackArea* mutable_black_area(int index);
  ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::BlackArea >*
      mutable_black_area();
  const ::cvte::hdmap::BlackArea& black_area(int index) const;
  ::cvte::hdmap::BlackArea* add_black_area();
  const ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::BlackArea >&
      black_area() const;

  // repeated .cvte.hdmap.PitArea pit_area = 23;
  int pit_area_size() const;
  void clear_pit_area();
  static const int kPitAreaFieldNumber = 23;
  ::cvte::hdmap::PitArea* mutable_pit_area(int index);
  ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::PitArea >*
      mutable_pit_area();
  const ::cvte::hdmap::PitArea& pit_area(int index) const;
  ::cvte::hdmap::PitArea* add_pit_area();
  const ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::PitArea >&
      pit_area() const;

  // optional .cvte.hdmap.Header header = 1;
  bool has_header() const;
  void clear_header();
  static const int kHeaderFieldNumber = 1;
  private:
  const ::cvte::hdmap::Header& _internal_header() const;
  public:
  const ::cvte::hdmap::Header& header() const;
  ::cvte::hdmap::Header* release_header();
  ::cvte::hdmap::Header* mutable_header();
  void set_allocated_header(::cvte::hdmap::Header* header);

  // @@protoc_insertion_point(class_scope:cvte.hdmap.Map)
 private:
  void set_has_header();
  void clear_has_header();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::Crosswalk > crosswalk_;
  ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::Junction > junction_;
  ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::Lane > lane_;
  ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::StopSign > stop_sign_;
  ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::Signal > signal_;
  ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::YieldSign > yield_;
  ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::Overlap > overlap_;
  ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::ClearArea > clear_area_;
  ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::SpeedBump > speed_bump_;
  ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::Road > road_;
  ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::ParkingSpace > parking_space_;
  ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::PNCJunction > pnc_junction_;
  ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::RSU > rsu_;
  ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::MapArea > map_area_;
  ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::CleanArea > clean_area_;
  ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::SlopeArea > slope_area_;
  ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::Elevator > elevator_;
  ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::NarrowArea > narrow_area_;
  ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::MarkArea > mark_area_;
  ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::ProhibitedArea > prohibited_area_;
  ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::BlackArea > black_area_;
  ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::PitArea > pit_area_;
  ::cvte::hdmap::Header* header_;
  friend struct ::protobuf_map_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Projection

// optional string proj = 1;
inline bool Projection::has_proj() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Projection::set_has_proj() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Projection::clear_has_proj() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Projection::clear_proj() {
  proj_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_proj();
}
inline const ::std::string& Projection::proj() const {
  // @@protoc_insertion_point(field_get:cvte.hdmap.Projection.proj)
  return proj_.GetNoArena();
}
inline void Projection::set_proj(const ::std::string& value) {
  set_has_proj();
  proj_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:cvte.hdmap.Projection.proj)
}
#if LANG_CXX11
inline void Projection::set_proj(::std::string&& value) {
  set_has_proj();
  proj_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:cvte.hdmap.Projection.proj)
}
#endif
inline void Projection::set_proj(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_proj();
  proj_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:cvte.hdmap.Projection.proj)
}
inline void Projection::set_proj(const char* value, size_t size) {
  set_has_proj();
  proj_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:cvte.hdmap.Projection.proj)
}
inline ::std::string* Projection::mutable_proj() {
  set_has_proj();
  // @@protoc_insertion_point(field_mutable:cvte.hdmap.Projection.proj)
  return proj_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Projection::release_proj() {
  // @@protoc_insertion_point(field_release:cvte.hdmap.Projection.proj)
  if (!has_proj()) {
    return NULL;
  }
  clear_has_proj();
  return proj_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Projection::set_allocated_proj(::std::string* proj) {
  if (proj != NULL) {
    set_has_proj();
  } else {
    clear_has_proj();
  }
  proj_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), proj);
  // @@protoc_insertion_point(field_set_allocated:cvte.hdmap.Projection.proj)
}

// -------------------------------------------------------------------

// Header

// optional bytes version = 1;
inline bool Header::has_version() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Header::set_has_version() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Header::clear_has_version() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Header::clear_version() {
  version_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_version();
}
inline const ::std::string& Header::version() const {
  // @@protoc_insertion_point(field_get:cvte.hdmap.Header.version)
  return version_.GetNoArena();
}
inline void Header::set_version(const ::std::string& value) {
  set_has_version();
  version_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:cvte.hdmap.Header.version)
}
#if LANG_CXX11
inline void Header::set_version(::std::string&& value) {
  set_has_version();
  version_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:cvte.hdmap.Header.version)
}
#endif
inline void Header::set_version(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_version();
  version_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:cvte.hdmap.Header.version)
}
inline void Header::set_version(const void* value, size_t size) {
  set_has_version();
  version_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:cvte.hdmap.Header.version)
}
inline ::std::string* Header::mutable_version() {
  set_has_version();
  // @@protoc_insertion_point(field_mutable:cvte.hdmap.Header.version)
  return version_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Header::release_version() {
  // @@protoc_insertion_point(field_release:cvte.hdmap.Header.version)
  if (!has_version()) {
    return NULL;
  }
  clear_has_version();
  return version_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Header::set_allocated_version(::std::string* version) {
  if (version != NULL) {
    set_has_version();
  } else {
    clear_has_version();
  }
  version_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), version);
  // @@protoc_insertion_point(field_set_allocated:cvte.hdmap.Header.version)
}

// optional bytes date = 2;
inline bool Header::has_date() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Header::set_has_date() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Header::clear_has_date() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Header::clear_date() {
  date_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_date();
}
inline const ::std::string& Header::date() const {
  // @@protoc_insertion_point(field_get:cvte.hdmap.Header.date)
  return date_.GetNoArena();
}
inline void Header::set_date(const ::std::string& value) {
  set_has_date();
  date_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:cvte.hdmap.Header.date)
}
#if LANG_CXX11
inline void Header::set_date(::std::string&& value) {
  set_has_date();
  date_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:cvte.hdmap.Header.date)
}
#endif
inline void Header::set_date(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_date();
  date_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:cvte.hdmap.Header.date)
}
inline void Header::set_date(const void* value, size_t size) {
  set_has_date();
  date_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:cvte.hdmap.Header.date)
}
inline ::std::string* Header::mutable_date() {
  set_has_date();
  // @@protoc_insertion_point(field_mutable:cvte.hdmap.Header.date)
  return date_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Header::release_date() {
  // @@protoc_insertion_point(field_release:cvte.hdmap.Header.date)
  if (!has_date()) {
    return NULL;
  }
  clear_has_date();
  return date_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Header::set_allocated_date(::std::string* date) {
  if (date != NULL) {
    set_has_date();
  } else {
    clear_has_date();
  }
  date_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), date);
  // @@protoc_insertion_point(field_set_allocated:cvte.hdmap.Header.date)
}

// optional .cvte.hdmap.Projection projection = 3;
inline bool Header::has_projection() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void Header::set_has_projection() {
  _has_bits_[0] |= 0x00000080u;
}
inline void Header::clear_has_projection() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void Header::clear_projection() {
  if (projection_ != NULL) projection_->Clear();
  clear_has_projection();
}
inline const ::cvte::hdmap::Projection& Header::_internal_projection() const {
  return *projection_;
}
inline const ::cvte::hdmap::Projection& Header::projection() const {
  const ::cvte::hdmap::Projection* p = projection_;
  // @@protoc_insertion_point(field_get:cvte.hdmap.Header.projection)
  return p != NULL ? *p : *reinterpret_cast<const ::cvte::hdmap::Projection*>(
      &::cvte::hdmap::_Projection_default_instance_);
}
inline ::cvte::hdmap::Projection* Header::release_projection() {
  // @@protoc_insertion_point(field_release:cvte.hdmap.Header.projection)
  clear_has_projection();
  ::cvte::hdmap::Projection* temp = projection_;
  projection_ = NULL;
  return temp;
}
inline ::cvte::hdmap::Projection* Header::mutable_projection() {
  set_has_projection();
  if (projection_ == NULL) {
    auto* p = CreateMaybeMessage<::cvte::hdmap::Projection>(GetArenaNoVirtual());
    projection_ = p;
  }
  // @@protoc_insertion_point(field_mutable:cvte.hdmap.Header.projection)
  return projection_;
}
inline void Header::set_allocated_projection(::cvte::hdmap::Projection* projection) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete projection_;
  }
  if (projection) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      projection = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, projection, submessage_arena);
    }
    set_has_projection();
  } else {
    clear_has_projection();
  }
  projection_ = projection;
  // @@protoc_insertion_point(field_set_allocated:cvte.hdmap.Header.projection)
}

// optional bytes district = 4;
inline bool Header::has_district() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Header::set_has_district() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Header::clear_has_district() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Header::clear_district() {
  district_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_district();
}
inline const ::std::string& Header::district() const {
  // @@protoc_insertion_point(field_get:cvte.hdmap.Header.district)
  return district_.GetNoArena();
}
inline void Header::set_district(const ::std::string& value) {
  set_has_district();
  district_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:cvte.hdmap.Header.district)
}
#if LANG_CXX11
inline void Header::set_district(::std::string&& value) {
  set_has_district();
  district_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:cvte.hdmap.Header.district)
}
#endif
inline void Header::set_district(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_district();
  district_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:cvte.hdmap.Header.district)
}
inline void Header::set_district(const void* value, size_t size) {
  set_has_district();
  district_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:cvte.hdmap.Header.district)
}
inline ::std::string* Header::mutable_district() {
  set_has_district();
  // @@protoc_insertion_point(field_mutable:cvte.hdmap.Header.district)
  return district_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Header::release_district() {
  // @@protoc_insertion_point(field_release:cvte.hdmap.Header.district)
  if (!has_district()) {
    return NULL;
  }
  clear_has_district();
  return district_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Header::set_allocated_district(::std::string* district) {
  if (district != NULL) {
    set_has_district();
  } else {
    clear_has_district();
  }
  district_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), district);
  // @@protoc_insertion_point(field_set_allocated:cvte.hdmap.Header.district)
}

// optional bytes generation = 5;
inline bool Header::has_generation() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Header::set_has_generation() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Header::clear_has_generation() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Header::clear_generation() {
  generation_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_generation();
}
inline const ::std::string& Header::generation() const {
  // @@protoc_insertion_point(field_get:cvte.hdmap.Header.generation)
  return generation_.GetNoArena();
}
inline void Header::set_generation(const ::std::string& value) {
  set_has_generation();
  generation_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:cvte.hdmap.Header.generation)
}
#if LANG_CXX11
inline void Header::set_generation(::std::string&& value) {
  set_has_generation();
  generation_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:cvte.hdmap.Header.generation)
}
#endif
inline void Header::set_generation(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_generation();
  generation_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:cvte.hdmap.Header.generation)
}
inline void Header::set_generation(const void* value, size_t size) {
  set_has_generation();
  generation_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:cvte.hdmap.Header.generation)
}
inline ::std::string* Header::mutable_generation() {
  set_has_generation();
  // @@protoc_insertion_point(field_mutable:cvte.hdmap.Header.generation)
  return generation_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Header::release_generation() {
  // @@protoc_insertion_point(field_release:cvte.hdmap.Header.generation)
  if (!has_generation()) {
    return NULL;
  }
  clear_has_generation();
  return generation_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Header::set_allocated_generation(::std::string* generation) {
  if (generation != NULL) {
    set_has_generation();
  } else {
    clear_has_generation();
  }
  generation_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), generation);
  // @@protoc_insertion_point(field_set_allocated:cvte.hdmap.Header.generation)
}

// optional bytes rev_major = 6;
inline bool Header::has_rev_major() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void Header::set_has_rev_major() {
  _has_bits_[0] |= 0x00000010u;
}
inline void Header::clear_has_rev_major() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void Header::clear_rev_major() {
  rev_major_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_rev_major();
}
inline const ::std::string& Header::rev_major() const {
  // @@protoc_insertion_point(field_get:cvte.hdmap.Header.rev_major)
  return rev_major_.GetNoArena();
}
inline void Header::set_rev_major(const ::std::string& value) {
  set_has_rev_major();
  rev_major_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:cvte.hdmap.Header.rev_major)
}
#if LANG_CXX11
inline void Header::set_rev_major(::std::string&& value) {
  set_has_rev_major();
  rev_major_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:cvte.hdmap.Header.rev_major)
}
#endif
inline void Header::set_rev_major(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_rev_major();
  rev_major_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:cvte.hdmap.Header.rev_major)
}
inline void Header::set_rev_major(const void* value, size_t size) {
  set_has_rev_major();
  rev_major_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:cvte.hdmap.Header.rev_major)
}
inline ::std::string* Header::mutable_rev_major() {
  set_has_rev_major();
  // @@protoc_insertion_point(field_mutable:cvte.hdmap.Header.rev_major)
  return rev_major_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Header::release_rev_major() {
  // @@protoc_insertion_point(field_release:cvte.hdmap.Header.rev_major)
  if (!has_rev_major()) {
    return NULL;
  }
  clear_has_rev_major();
  return rev_major_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Header::set_allocated_rev_major(::std::string* rev_major) {
  if (rev_major != NULL) {
    set_has_rev_major();
  } else {
    clear_has_rev_major();
  }
  rev_major_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), rev_major);
  // @@protoc_insertion_point(field_set_allocated:cvte.hdmap.Header.rev_major)
}

// optional bytes rev_minor = 7;
inline bool Header::has_rev_minor() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void Header::set_has_rev_minor() {
  _has_bits_[0] |= 0x00000020u;
}
inline void Header::clear_has_rev_minor() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void Header::clear_rev_minor() {
  rev_minor_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_rev_minor();
}
inline const ::std::string& Header::rev_minor() const {
  // @@protoc_insertion_point(field_get:cvte.hdmap.Header.rev_minor)
  return rev_minor_.GetNoArena();
}
inline void Header::set_rev_minor(const ::std::string& value) {
  set_has_rev_minor();
  rev_minor_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:cvte.hdmap.Header.rev_minor)
}
#if LANG_CXX11
inline void Header::set_rev_minor(::std::string&& value) {
  set_has_rev_minor();
  rev_minor_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:cvte.hdmap.Header.rev_minor)
}
#endif
inline void Header::set_rev_minor(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_rev_minor();
  rev_minor_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:cvte.hdmap.Header.rev_minor)
}
inline void Header::set_rev_minor(const void* value, size_t size) {
  set_has_rev_minor();
  rev_minor_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:cvte.hdmap.Header.rev_minor)
}
inline ::std::string* Header::mutable_rev_minor() {
  set_has_rev_minor();
  // @@protoc_insertion_point(field_mutable:cvte.hdmap.Header.rev_minor)
  return rev_minor_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Header::release_rev_minor() {
  // @@protoc_insertion_point(field_release:cvte.hdmap.Header.rev_minor)
  if (!has_rev_minor()) {
    return NULL;
  }
  clear_has_rev_minor();
  return rev_minor_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Header::set_allocated_rev_minor(::std::string* rev_minor) {
  if (rev_minor != NULL) {
    set_has_rev_minor();
  } else {
    clear_has_rev_minor();
  }
  rev_minor_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), rev_minor);
  // @@protoc_insertion_point(field_set_allocated:cvte.hdmap.Header.rev_minor)
}

// optional double left = 8;
inline bool Header::has_left() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void Header::set_has_left() {
  _has_bits_[0] |= 0x00000100u;
}
inline void Header::clear_has_left() {
  _has_bits_[0] &= ~0x00000100u;
}
inline void Header::clear_left() {
  left_ = 0;
  clear_has_left();
}
inline double Header::left() const {
  // @@protoc_insertion_point(field_get:cvte.hdmap.Header.left)
  return left_;
}
inline void Header::set_left(double value) {
  set_has_left();
  left_ = value;
  // @@protoc_insertion_point(field_set:cvte.hdmap.Header.left)
}

// optional double top = 9;
inline bool Header::has_top() const {
  return (_has_bits_[0] & 0x00000200u) != 0;
}
inline void Header::set_has_top() {
  _has_bits_[0] |= 0x00000200u;
}
inline void Header::clear_has_top() {
  _has_bits_[0] &= ~0x00000200u;
}
inline void Header::clear_top() {
  top_ = 0;
  clear_has_top();
}
inline double Header::top() const {
  // @@protoc_insertion_point(field_get:cvte.hdmap.Header.top)
  return top_;
}
inline void Header::set_top(double value) {
  set_has_top();
  top_ = value;
  // @@protoc_insertion_point(field_set:cvte.hdmap.Header.top)
}

// optional double right = 10;
inline bool Header::has_right() const {
  return (_has_bits_[0] & 0x00000400u) != 0;
}
inline void Header::set_has_right() {
  _has_bits_[0] |= 0x00000400u;
}
inline void Header::clear_has_right() {
  _has_bits_[0] &= ~0x00000400u;
}
inline void Header::clear_right() {
  right_ = 0;
  clear_has_right();
}
inline double Header::right() const {
  // @@protoc_insertion_point(field_get:cvte.hdmap.Header.right)
  return right_;
}
inline void Header::set_right(double value) {
  set_has_right();
  right_ = value;
  // @@protoc_insertion_point(field_set:cvte.hdmap.Header.right)
}

// optional double bottom = 11;
inline bool Header::has_bottom() const {
  return (_has_bits_[0] & 0x00000800u) != 0;
}
inline void Header::set_has_bottom() {
  _has_bits_[0] |= 0x00000800u;
}
inline void Header::clear_has_bottom() {
  _has_bits_[0] &= ~0x00000800u;
}
inline void Header::clear_bottom() {
  bottom_ = 0;
  clear_has_bottom();
}
inline double Header::bottom() const {
  // @@protoc_insertion_point(field_get:cvte.hdmap.Header.bottom)
  return bottom_;
}
inline void Header::set_bottom(double value) {
  set_has_bottom();
  bottom_ = value;
  // @@protoc_insertion_point(field_set:cvte.hdmap.Header.bottom)
}

// optional bytes vendor = 12;
inline bool Header::has_vendor() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void Header::set_has_vendor() {
  _has_bits_[0] |= 0x00000040u;
}
inline void Header::clear_has_vendor() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void Header::clear_vendor() {
  vendor_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_vendor();
}
inline const ::std::string& Header::vendor() const {
  // @@protoc_insertion_point(field_get:cvte.hdmap.Header.vendor)
  return vendor_.GetNoArena();
}
inline void Header::set_vendor(const ::std::string& value) {
  set_has_vendor();
  vendor_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:cvte.hdmap.Header.vendor)
}
#if LANG_CXX11
inline void Header::set_vendor(::std::string&& value) {
  set_has_vendor();
  vendor_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:cvte.hdmap.Header.vendor)
}
#endif
inline void Header::set_vendor(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_vendor();
  vendor_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:cvte.hdmap.Header.vendor)
}
inline void Header::set_vendor(const void* value, size_t size) {
  set_has_vendor();
  vendor_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:cvte.hdmap.Header.vendor)
}
inline ::std::string* Header::mutable_vendor() {
  set_has_vendor();
  // @@protoc_insertion_point(field_mutable:cvte.hdmap.Header.vendor)
  return vendor_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Header::release_vendor() {
  // @@protoc_insertion_point(field_release:cvte.hdmap.Header.vendor)
  if (!has_vendor()) {
    return NULL;
  }
  clear_has_vendor();
  return vendor_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Header::set_allocated_vendor(::std::string* vendor) {
  if (vendor != NULL) {
    set_has_vendor();
  } else {
    clear_has_vendor();
  }
  vendor_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), vendor);
  // @@protoc_insertion_point(field_set_allocated:cvte.hdmap.Header.vendor)
}

// -------------------------------------------------------------------

// Map

// optional .cvte.hdmap.Header header = 1;
inline bool Map::has_header() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Map::set_has_header() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Map::clear_has_header() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Map::clear_header() {
  if (header_ != NULL) header_->Clear();
  clear_has_header();
}
inline const ::cvte::hdmap::Header& Map::_internal_header() const {
  return *header_;
}
inline const ::cvte::hdmap::Header& Map::header() const {
  const ::cvte::hdmap::Header* p = header_;
  // @@protoc_insertion_point(field_get:cvte.hdmap.Map.header)
  return p != NULL ? *p : *reinterpret_cast<const ::cvte::hdmap::Header*>(
      &::cvte::hdmap::_Header_default_instance_);
}
inline ::cvte::hdmap::Header* Map::release_header() {
  // @@protoc_insertion_point(field_release:cvte.hdmap.Map.header)
  clear_has_header();
  ::cvte::hdmap::Header* temp = header_;
  header_ = NULL;
  return temp;
}
inline ::cvte::hdmap::Header* Map::mutable_header() {
  set_has_header();
  if (header_ == NULL) {
    auto* p = CreateMaybeMessage<::cvte::hdmap::Header>(GetArenaNoVirtual());
    header_ = p;
  }
  // @@protoc_insertion_point(field_mutable:cvte.hdmap.Map.header)
  return header_;
}
inline void Map::set_allocated_header(::cvte::hdmap::Header* header) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete header_;
  }
  if (header) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      header = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, header, submessage_arena);
    }
    set_has_header();
  } else {
    clear_has_header();
  }
  header_ = header;
  // @@protoc_insertion_point(field_set_allocated:cvte.hdmap.Map.header)
}

// repeated .cvte.hdmap.Crosswalk crosswalk = 2;
inline int Map::crosswalk_size() const {
  return crosswalk_.size();
}
inline ::cvte::hdmap::Crosswalk* Map::mutable_crosswalk(int index) {
  // @@protoc_insertion_point(field_mutable:cvte.hdmap.Map.crosswalk)
  return crosswalk_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::Crosswalk >*
Map::mutable_crosswalk() {
  // @@protoc_insertion_point(field_mutable_list:cvte.hdmap.Map.crosswalk)
  return &crosswalk_;
}
inline const ::cvte::hdmap::Crosswalk& Map::crosswalk(int index) const {
  // @@protoc_insertion_point(field_get:cvte.hdmap.Map.crosswalk)
  return crosswalk_.Get(index);
}
inline ::cvte::hdmap::Crosswalk* Map::add_crosswalk() {
  // @@protoc_insertion_point(field_add:cvte.hdmap.Map.crosswalk)
  return crosswalk_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::Crosswalk >&
Map::crosswalk() const {
  // @@protoc_insertion_point(field_list:cvte.hdmap.Map.crosswalk)
  return crosswalk_;
}

// repeated .cvte.hdmap.Junction junction = 3;
inline int Map::junction_size() const {
  return junction_.size();
}
inline ::cvte::hdmap::Junction* Map::mutable_junction(int index) {
  // @@protoc_insertion_point(field_mutable:cvte.hdmap.Map.junction)
  return junction_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::Junction >*
Map::mutable_junction() {
  // @@protoc_insertion_point(field_mutable_list:cvte.hdmap.Map.junction)
  return &junction_;
}
inline const ::cvte::hdmap::Junction& Map::junction(int index) const {
  // @@protoc_insertion_point(field_get:cvte.hdmap.Map.junction)
  return junction_.Get(index);
}
inline ::cvte::hdmap::Junction* Map::add_junction() {
  // @@protoc_insertion_point(field_add:cvte.hdmap.Map.junction)
  return junction_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::Junction >&
Map::junction() const {
  // @@protoc_insertion_point(field_list:cvte.hdmap.Map.junction)
  return junction_;
}

// repeated .cvte.hdmap.Lane lane = 4;
inline int Map::lane_size() const {
  return lane_.size();
}
inline ::cvte::hdmap::Lane* Map::mutable_lane(int index) {
  // @@protoc_insertion_point(field_mutable:cvte.hdmap.Map.lane)
  return lane_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::Lane >*
Map::mutable_lane() {
  // @@protoc_insertion_point(field_mutable_list:cvte.hdmap.Map.lane)
  return &lane_;
}
inline const ::cvte::hdmap::Lane& Map::lane(int index) const {
  // @@protoc_insertion_point(field_get:cvte.hdmap.Map.lane)
  return lane_.Get(index);
}
inline ::cvte::hdmap::Lane* Map::add_lane() {
  // @@protoc_insertion_point(field_add:cvte.hdmap.Map.lane)
  return lane_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::Lane >&
Map::lane() const {
  // @@protoc_insertion_point(field_list:cvte.hdmap.Map.lane)
  return lane_;
}

// repeated .cvte.hdmap.StopSign stop_sign = 5;
inline int Map::stop_sign_size() const {
  return stop_sign_.size();
}
inline ::cvte::hdmap::StopSign* Map::mutable_stop_sign(int index) {
  // @@protoc_insertion_point(field_mutable:cvte.hdmap.Map.stop_sign)
  return stop_sign_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::StopSign >*
Map::mutable_stop_sign() {
  // @@protoc_insertion_point(field_mutable_list:cvte.hdmap.Map.stop_sign)
  return &stop_sign_;
}
inline const ::cvte::hdmap::StopSign& Map::stop_sign(int index) const {
  // @@protoc_insertion_point(field_get:cvte.hdmap.Map.stop_sign)
  return stop_sign_.Get(index);
}
inline ::cvte::hdmap::StopSign* Map::add_stop_sign() {
  // @@protoc_insertion_point(field_add:cvte.hdmap.Map.stop_sign)
  return stop_sign_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::StopSign >&
Map::stop_sign() const {
  // @@protoc_insertion_point(field_list:cvte.hdmap.Map.stop_sign)
  return stop_sign_;
}

// repeated .cvte.hdmap.Signal signal = 6;
inline int Map::signal_size() const {
  return signal_.size();
}
inline ::cvte::hdmap::Signal* Map::mutable_signal(int index) {
  // @@protoc_insertion_point(field_mutable:cvte.hdmap.Map.signal)
  return signal_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::Signal >*
Map::mutable_signal() {
  // @@protoc_insertion_point(field_mutable_list:cvte.hdmap.Map.signal)
  return &signal_;
}
inline const ::cvte::hdmap::Signal& Map::signal(int index) const {
  // @@protoc_insertion_point(field_get:cvte.hdmap.Map.signal)
  return signal_.Get(index);
}
inline ::cvte::hdmap::Signal* Map::add_signal() {
  // @@protoc_insertion_point(field_add:cvte.hdmap.Map.signal)
  return signal_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::Signal >&
Map::signal() const {
  // @@protoc_insertion_point(field_list:cvte.hdmap.Map.signal)
  return signal_;
}

// repeated .cvte.hdmap.YieldSign yield = 7;
inline int Map::yield_size() const {
  return yield_.size();
}
inline ::cvte::hdmap::YieldSign* Map::mutable_yield(int index) {
  // @@protoc_insertion_point(field_mutable:cvte.hdmap.Map.yield)
  return yield_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::YieldSign >*
Map::mutable_yield() {
  // @@protoc_insertion_point(field_mutable_list:cvte.hdmap.Map.yield)
  return &yield_;
}
inline const ::cvte::hdmap::YieldSign& Map::yield(int index) const {
  // @@protoc_insertion_point(field_get:cvte.hdmap.Map.yield)
  return yield_.Get(index);
}
inline ::cvte::hdmap::YieldSign* Map::add_yield() {
  // @@protoc_insertion_point(field_add:cvte.hdmap.Map.yield)
  return yield_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::YieldSign >&
Map::yield() const {
  // @@protoc_insertion_point(field_list:cvte.hdmap.Map.yield)
  return yield_;
}

// repeated .cvte.hdmap.Overlap overlap = 8;
inline int Map::overlap_size() const {
  return overlap_.size();
}
inline ::cvte::hdmap::Overlap* Map::mutable_overlap(int index) {
  // @@protoc_insertion_point(field_mutable:cvte.hdmap.Map.overlap)
  return overlap_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::Overlap >*
Map::mutable_overlap() {
  // @@protoc_insertion_point(field_mutable_list:cvte.hdmap.Map.overlap)
  return &overlap_;
}
inline const ::cvte::hdmap::Overlap& Map::overlap(int index) const {
  // @@protoc_insertion_point(field_get:cvte.hdmap.Map.overlap)
  return overlap_.Get(index);
}
inline ::cvte::hdmap::Overlap* Map::add_overlap() {
  // @@protoc_insertion_point(field_add:cvte.hdmap.Map.overlap)
  return overlap_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::Overlap >&
Map::overlap() const {
  // @@protoc_insertion_point(field_list:cvte.hdmap.Map.overlap)
  return overlap_;
}

// repeated .cvte.hdmap.ClearArea clear_area = 9;
inline int Map::clear_area_size() const {
  return clear_area_.size();
}
inline ::cvte::hdmap::ClearArea* Map::mutable_clear_area(int index) {
  // @@protoc_insertion_point(field_mutable:cvte.hdmap.Map.clear_area)
  return clear_area_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::ClearArea >*
Map::mutable_clear_area() {
  // @@protoc_insertion_point(field_mutable_list:cvte.hdmap.Map.clear_area)
  return &clear_area_;
}
inline const ::cvte::hdmap::ClearArea& Map::clear_area(int index) const {
  // @@protoc_insertion_point(field_get:cvte.hdmap.Map.clear_area)
  return clear_area_.Get(index);
}
inline ::cvte::hdmap::ClearArea* Map::add_clear_area() {
  // @@protoc_insertion_point(field_add:cvte.hdmap.Map.clear_area)
  return clear_area_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::ClearArea >&
Map::clear_area() const {
  // @@protoc_insertion_point(field_list:cvte.hdmap.Map.clear_area)
  return clear_area_;
}

// repeated .cvte.hdmap.SpeedBump speed_bump = 10;
inline int Map::speed_bump_size() const {
  return speed_bump_.size();
}
inline ::cvte::hdmap::SpeedBump* Map::mutable_speed_bump(int index) {
  // @@protoc_insertion_point(field_mutable:cvte.hdmap.Map.speed_bump)
  return speed_bump_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::SpeedBump >*
Map::mutable_speed_bump() {
  // @@protoc_insertion_point(field_mutable_list:cvte.hdmap.Map.speed_bump)
  return &speed_bump_;
}
inline const ::cvte::hdmap::SpeedBump& Map::speed_bump(int index) const {
  // @@protoc_insertion_point(field_get:cvte.hdmap.Map.speed_bump)
  return speed_bump_.Get(index);
}
inline ::cvte::hdmap::SpeedBump* Map::add_speed_bump() {
  // @@protoc_insertion_point(field_add:cvte.hdmap.Map.speed_bump)
  return speed_bump_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::SpeedBump >&
Map::speed_bump() const {
  // @@protoc_insertion_point(field_list:cvte.hdmap.Map.speed_bump)
  return speed_bump_;
}

// repeated .cvte.hdmap.Road road = 11;
inline int Map::road_size() const {
  return road_.size();
}
inline ::cvte::hdmap::Road* Map::mutable_road(int index) {
  // @@protoc_insertion_point(field_mutable:cvte.hdmap.Map.road)
  return road_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::Road >*
Map::mutable_road() {
  // @@protoc_insertion_point(field_mutable_list:cvte.hdmap.Map.road)
  return &road_;
}
inline const ::cvte::hdmap::Road& Map::road(int index) const {
  // @@protoc_insertion_point(field_get:cvte.hdmap.Map.road)
  return road_.Get(index);
}
inline ::cvte::hdmap::Road* Map::add_road() {
  // @@protoc_insertion_point(field_add:cvte.hdmap.Map.road)
  return road_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::Road >&
Map::road() const {
  // @@protoc_insertion_point(field_list:cvte.hdmap.Map.road)
  return road_;
}

// repeated .cvte.hdmap.ParkingSpace parking_space = 12;
inline int Map::parking_space_size() const {
  return parking_space_.size();
}
inline ::cvte::hdmap::ParkingSpace* Map::mutable_parking_space(int index) {
  // @@protoc_insertion_point(field_mutable:cvte.hdmap.Map.parking_space)
  return parking_space_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::ParkingSpace >*
Map::mutable_parking_space() {
  // @@protoc_insertion_point(field_mutable_list:cvte.hdmap.Map.parking_space)
  return &parking_space_;
}
inline const ::cvte::hdmap::ParkingSpace& Map::parking_space(int index) const {
  // @@protoc_insertion_point(field_get:cvte.hdmap.Map.parking_space)
  return parking_space_.Get(index);
}
inline ::cvte::hdmap::ParkingSpace* Map::add_parking_space() {
  // @@protoc_insertion_point(field_add:cvte.hdmap.Map.parking_space)
  return parking_space_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::ParkingSpace >&
Map::parking_space() const {
  // @@protoc_insertion_point(field_list:cvte.hdmap.Map.parking_space)
  return parking_space_;
}

// repeated .cvte.hdmap.PNCJunction pnc_junction = 13;
inline int Map::pnc_junction_size() const {
  return pnc_junction_.size();
}
inline ::cvte::hdmap::PNCJunction* Map::mutable_pnc_junction(int index) {
  // @@protoc_insertion_point(field_mutable:cvte.hdmap.Map.pnc_junction)
  return pnc_junction_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::PNCJunction >*
Map::mutable_pnc_junction() {
  // @@protoc_insertion_point(field_mutable_list:cvte.hdmap.Map.pnc_junction)
  return &pnc_junction_;
}
inline const ::cvte::hdmap::PNCJunction& Map::pnc_junction(int index) const {
  // @@protoc_insertion_point(field_get:cvte.hdmap.Map.pnc_junction)
  return pnc_junction_.Get(index);
}
inline ::cvte::hdmap::PNCJunction* Map::add_pnc_junction() {
  // @@protoc_insertion_point(field_add:cvte.hdmap.Map.pnc_junction)
  return pnc_junction_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::PNCJunction >&
Map::pnc_junction() const {
  // @@protoc_insertion_point(field_list:cvte.hdmap.Map.pnc_junction)
  return pnc_junction_;
}

// repeated .cvte.hdmap.RSU rsu = 14;
inline int Map::rsu_size() const {
  return rsu_.size();
}
inline ::cvte::hdmap::RSU* Map::mutable_rsu(int index) {
  // @@protoc_insertion_point(field_mutable:cvte.hdmap.Map.rsu)
  return rsu_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::RSU >*
Map::mutable_rsu() {
  // @@protoc_insertion_point(field_mutable_list:cvte.hdmap.Map.rsu)
  return &rsu_;
}
inline const ::cvte::hdmap::RSU& Map::rsu(int index) const {
  // @@protoc_insertion_point(field_get:cvte.hdmap.Map.rsu)
  return rsu_.Get(index);
}
inline ::cvte::hdmap::RSU* Map::add_rsu() {
  // @@protoc_insertion_point(field_add:cvte.hdmap.Map.rsu)
  return rsu_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::RSU >&
Map::rsu() const {
  // @@protoc_insertion_point(field_list:cvte.hdmap.Map.rsu)
  return rsu_;
}

// repeated .cvte.hdmap.MapArea map_area = 15;
inline int Map::map_area_size() const {
  return map_area_.size();
}
inline ::cvte::hdmap::MapArea* Map::mutable_map_area(int index) {
  // @@protoc_insertion_point(field_mutable:cvte.hdmap.Map.map_area)
  return map_area_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::MapArea >*
Map::mutable_map_area() {
  // @@protoc_insertion_point(field_mutable_list:cvte.hdmap.Map.map_area)
  return &map_area_;
}
inline const ::cvte::hdmap::MapArea& Map::map_area(int index) const {
  // @@protoc_insertion_point(field_get:cvte.hdmap.Map.map_area)
  return map_area_.Get(index);
}
inline ::cvte::hdmap::MapArea* Map::add_map_area() {
  // @@protoc_insertion_point(field_add:cvte.hdmap.Map.map_area)
  return map_area_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::MapArea >&
Map::map_area() const {
  // @@protoc_insertion_point(field_list:cvte.hdmap.Map.map_area)
  return map_area_;
}

// repeated .cvte.hdmap.CleanArea clean_area = 16;
inline int Map::clean_area_size() const {
  return clean_area_.size();
}
inline ::cvte::hdmap::CleanArea* Map::mutable_clean_area(int index) {
  // @@protoc_insertion_point(field_mutable:cvte.hdmap.Map.clean_area)
  return clean_area_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::CleanArea >*
Map::mutable_clean_area() {
  // @@protoc_insertion_point(field_mutable_list:cvte.hdmap.Map.clean_area)
  return &clean_area_;
}
inline const ::cvte::hdmap::CleanArea& Map::clean_area(int index) const {
  // @@protoc_insertion_point(field_get:cvte.hdmap.Map.clean_area)
  return clean_area_.Get(index);
}
inline ::cvte::hdmap::CleanArea* Map::add_clean_area() {
  // @@protoc_insertion_point(field_add:cvte.hdmap.Map.clean_area)
  return clean_area_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::CleanArea >&
Map::clean_area() const {
  // @@protoc_insertion_point(field_list:cvte.hdmap.Map.clean_area)
  return clean_area_;
}

// repeated .cvte.hdmap.SlopeArea slope_area = 17;
inline int Map::slope_area_size() const {
  return slope_area_.size();
}
inline ::cvte::hdmap::SlopeArea* Map::mutable_slope_area(int index) {
  // @@protoc_insertion_point(field_mutable:cvte.hdmap.Map.slope_area)
  return slope_area_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::SlopeArea >*
Map::mutable_slope_area() {
  // @@protoc_insertion_point(field_mutable_list:cvte.hdmap.Map.slope_area)
  return &slope_area_;
}
inline const ::cvte::hdmap::SlopeArea& Map::slope_area(int index) const {
  // @@protoc_insertion_point(field_get:cvte.hdmap.Map.slope_area)
  return slope_area_.Get(index);
}
inline ::cvte::hdmap::SlopeArea* Map::add_slope_area() {
  // @@protoc_insertion_point(field_add:cvte.hdmap.Map.slope_area)
  return slope_area_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::SlopeArea >&
Map::slope_area() const {
  // @@protoc_insertion_point(field_list:cvte.hdmap.Map.slope_area)
  return slope_area_;
}

// repeated .cvte.hdmap.Elevator elevator = 18;
inline int Map::elevator_size() const {
  return elevator_.size();
}
inline ::cvte::hdmap::Elevator* Map::mutable_elevator(int index) {
  // @@protoc_insertion_point(field_mutable:cvte.hdmap.Map.elevator)
  return elevator_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::Elevator >*
Map::mutable_elevator() {
  // @@protoc_insertion_point(field_mutable_list:cvte.hdmap.Map.elevator)
  return &elevator_;
}
inline const ::cvte::hdmap::Elevator& Map::elevator(int index) const {
  // @@protoc_insertion_point(field_get:cvte.hdmap.Map.elevator)
  return elevator_.Get(index);
}
inline ::cvte::hdmap::Elevator* Map::add_elevator() {
  // @@protoc_insertion_point(field_add:cvte.hdmap.Map.elevator)
  return elevator_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::Elevator >&
Map::elevator() const {
  // @@protoc_insertion_point(field_list:cvte.hdmap.Map.elevator)
  return elevator_;
}

// repeated .cvte.hdmap.NarrowArea narrow_area = 19;
inline int Map::narrow_area_size() const {
  return narrow_area_.size();
}
inline ::cvte::hdmap::NarrowArea* Map::mutable_narrow_area(int index) {
  // @@protoc_insertion_point(field_mutable:cvte.hdmap.Map.narrow_area)
  return narrow_area_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::NarrowArea >*
Map::mutable_narrow_area() {
  // @@protoc_insertion_point(field_mutable_list:cvte.hdmap.Map.narrow_area)
  return &narrow_area_;
}
inline const ::cvte::hdmap::NarrowArea& Map::narrow_area(int index) const {
  // @@protoc_insertion_point(field_get:cvte.hdmap.Map.narrow_area)
  return narrow_area_.Get(index);
}
inline ::cvte::hdmap::NarrowArea* Map::add_narrow_area() {
  // @@protoc_insertion_point(field_add:cvte.hdmap.Map.narrow_area)
  return narrow_area_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::NarrowArea >&
Map::narrow_area() const {
  // @@protoc_insertion_point(field_list:cvte.hdmap.Map.narrow_area)
  return narrow_area_;
}

// repeated .cvte.hdmap.MarkArea mark_area = 20;
inline int Map::mark_area_size() const {
  return mark_area_.size();
}
inline ::cvte::hdmap::MarkArea* Map::mutable_mark_area(int index) {
  // @@protoc_insertion_point(field_mutable:cvte.hdmap.Map.mark_area)
  return mark_area_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::MarkArea >*
Map::mutable_mark_area() {
  // @@protoc_insertion_point(field_mutable_list:cvte.hdmap.Map.mark_area)
  return &mark_area_;
}
inline const ::cvte::hdmap::MarkArea& Map::mark_area(int index) const {
  // @@protoc_insertion_point(field_get:cvte.hdmap.Map.mark_area)
  return mark_area_.Get(index);
}
inline ::cvte::hdmap::MarkArea* Map::add_mark_area() {
  // @@protoc_insertion_point(field_add:cvte.hdmap.Map.mark_area)
  return mark_area_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::MarkArea >&
Map::mark_area() const {
  // @@protoc_insertion_point(field_list:cvte.hdmap.Map.mark_area)
  return mark_area_;
}

// repeated .cvte.hdmap.ProhibitedArea prohibited_area = 21;
inline int Map::prohibited_area_size() const {
  return prohibited_area_.size();
}
inline ::cvte::hdmap::ProhibitedArea* Map::mutable_prohibited_area(int index) {
  // @@protoc_insertion_point(field_mutable:cvte.hdmap.Map.prohibited_area)
  return prohibited_area_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::ProhibitedArea >*
Map::mutable_prohibited_area() {
  // @@protoc_insertion_point(field_mutable_list:cvte.hdmap.Map.prohibited_area)
  return &prohibited_area_;
}
inline const ::cvte::hdmap::ProhibitedArea& Map::prohibited_area(int index) const {
  // @@protoc_insertion_point(field_get:cvte.hdmap.Map.prohibited_area)
  return prohibited_area_.Get(index);
}
inline ::cvte::hdmap::ProhibitedArea* Map::add_prohibited_area() {
  // @@protoc_insertion_point(field_add:cvte.hdmap.Map.prohibited_area)
  return prohibited_area_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::ProhibitedArea >&
Map::prohibited_area() const {
  // @@protoc_insertion_point(field_list:cvte.hdmap.Map.prohibited_area)
  return prohibited_area_;
}

// repeated .cvte.hdmap.BlackArea black_area = 22;
inline int Map::black_area_size() const {
  return black_area_.size();
}
inline ::cvte::hdmap::BlackArea* Map::mutable_black_area(int index) {
  // @@protoc_insertion_point(field_mutable:cvte.hdmap.Map.black_area)
  return black_area_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::BlackArea >*
Map::mutable_black_area() {
  // @@protoc_insertion_point(field_mutable_list:cvte.hdmap.Map.black_area)
  return &black_area_;
}
inline const ::cvte::hdmap::BlackArea& Map::black_area(int index) const {
  // @@protoc_insertion_point(field_get:cvte.hdmap.Map.black_area)
  return black_area_.Get(index);
}
inline ::cvte::hdmap::BlackArea* Map::add_black_area() {
  // @@protoc_insertion_point(field_add:cvte.hdmap.Map.black_area)
  return black_area_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::BlackArea >&
Map::black_area() const {
  // @@protoc_insertion_point(field_list:cvte.hdmap.Map.black_area)
  return black_area_;
}

// repeated .cvte.hdmap.PitArea pit_area = 23;
inline int Map::pit_area_size() const {
  return pit_area_.size();
}
inline ::cvte::hdmap::PitArea* Map::mutable_pit_area(int index) {
  // @@protoc_insertion_point(field_mutable:cvte.hdmap.Map.pit_area)
  return pit_area_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::PitArea >*
Map::mutable_pit_area() {
  // @@protoc_insertion_point(field_mutable_list:cvte.hdmap.Map.pit_area)
  return &pit_area_;
}
inline const ::cvte::hdmap::PitArea& Map::pit_area(int index) const {
  // @@protoc_insertion_point(field_get:cvte.hdmap.Map.pit_area)
  return pit_area_.Get(index);
}
inline ::cvte::hdmap::PitArea* Map::add_pit_area() {
  // @@protoc_insertion_point(field_add:cvte.hdmap.Map.pit_area)
  return pit_area_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::PitArea >&
Map::pit_area() const {
  // @@protoc_insertion_point(field_list:cvte.hdmap.Map.pit_area)
  return pit_area_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace hdmap
}  // namespace cvte

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_map_2eproto
