// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: map_road.proto

#ifndef PROTOBUF_INCLUDED_map_5froad_2eproto
#define PROTOBUF_INCLUDED_map_5froad_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "map_geometry.pb.h"
#include "map_id.pb.h"
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_map_5froad_2eproto 

namespace protobuf_map_5froad_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[6];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_map_5froad_2eproto
namespace cvte {
namespace hdmap {
class BoundaryEdge;
class BoundaryEdgeDefaultTypeInternal;
extern BoundaryEdgeDefaultTypeInternal _BoundaryEdge_default_instance_;
class BoundaryPolygon;
class BoundaryPolygonDefaultTypeInternal;
extern BoundaryPolygonDefaultTypeInternal _BoundaryPolygon_default_instance_;
class Road;
class RoadDefaultTypeInternal;
extern RoadDefaultTypeInternal _Road_default_instance_;
class RoadBoundary;
class RoadBoundaryDefaultTypeInternal;
extern RoadBoundaryDefaultTypeInternal _RoadBoundary_default_instance_;
class RoadROIBoundary;
class RoadROIBoundaryDefaultTypeInternal;
extern RoadROIBoundaryDefaultTypeInternal _RoadROIBoundary_default_instance_;
class RoadSection;
class RoadSectionDefaultTypeInternal;
extern RoadSectionDefaultTypeInternal _RoadSection_default_instance_;
}  // namespace hdmap
}  // namespace cvte
namespace google {
namespace protobuf {
template<> ::cvte::hdmap::BoundaryEdge* Arena::CreateMaybeMessage<::cvte::hdmap::BoundaryEdge>(Arena*);
template<> ::cvte::hdmap::BoundaryPolygon* Arena::CreateMaybeMessage<::cvte::hdmap::BoundaryPolygon>(Arena*);
template<> ::cvte::hdmap::Road* Arena::CreateMaybeMessage<::cvte::hdmap::Road>(Arena*);
template<> ::cvte::hdmap::RoadBoundary* Arena::CreateMaybeMessage<::cvte::hdmap::RoadBoundary>(Arena*);
template<> ::cvte::hdmap::RoadROIBoundary* Arena::CreateMaybeMessage<::cvte::hdmap::RoadROIBoundary>(Arena*);
template<> ::cvte::hdmap::RoadSection* Arena::CreateMaybeMessage<::cvte::hdmap::RoadSection>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace cvte {
namespace hdmap {

enum BoundaryEdge_Type {
  BoundaryEdge_Type_UNKNOWN = 0,
  BoundaryEdge_Type_NORMAL = 1,
  BoundaryEdge_Type_LEFT_BOUNDARY = 2,
  BoundaryEdge_Type_RIGHT_BOUNDARY = 3
};
bool BoundaryEdge_Type_IsValid(int value);
const BoundaryEdge_Type BoundaryEdge_Type_Type_MIN = BoundaryEdge_Type_UNKNOWN;
const BoundaryEdge_Type BoundaryEdge_Type_Type_MAX = BoundaryEdge_Type_RIGHT_BOUNDARY;
const int BoundaryEdge_Type_Type_ARRAYSIZE = BoundaryEdge_Type_Type_MAX + 1;

const ::google::protobuf::EnumDescriptor* BoundaryEdge_Type_descriptor();
inline const ::std::string& BoundaryEdge_Type_Name(BoundaryEdge_Type value) {
  return ::google::protobuf::internal::NameOfEnum(
    BoundaryEdge_Type_descriptor(), value);
}
inline bool BoundaryEdge_Type_Parse(
    const ::std::string& name, BoundaryEdge_Type* value) {
  return ::google::protobuf::internal::ParseNamedEnum<BoundaryEdge_Type>(
    BoundaryEdge_Type_descriptor(), name, value);
}
enum Road_Type {
  Road_Type_UNKNOWN = 0,
  Road_Type_HIGHWAY = 1,
  Road_Type_CITY_ROAD = 2,
  Road_Type_PARK = 3
};
bool Road_Type_IsValid(int value);
const Road_Type Road_Type_Type_MIN = Road_Type_UNKNOWN;
const Road_Type Road_Type_Type_MAX = Road_Type_PARK;
const int Road_Type_Type_ARRAYSIZE = Road_Type_Type_MAX + 1;

const ::google::protobuf::EnumDescriptor* Road_Type_descriptor();
inline const ::std::string& Road_Type_Name(Road_Type value) {
  return ::google::protobuf::internal::NameOfEnum(
    Road_Type_descriptor(), value);
}
inline bool Road_Type_Parse(
    const ::std::string& name, Road_Type* value) {
  return ::google::protobuf::internal::ParseNamedEnum<Road_Type>(
    Road_Type_descriptor(), name, value);
}
// ===================================================================

class BoundaryEdge : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:cvte.hdmap.BoundaryEdge) */ {
 public:
  BoundaryEdge();
  virtual ~BoundaryEdge();

  BoundaryEdge(const BoundaryEdge& from);

  inline BoundaryEdge& operator=(const BoundaryEdge& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  BoundaryEdge(BoundaryEdge&& from) noexcept
    : BoundaryEdge() {
    *this = ::std::move(from);
  }

  inline BoundaryEdge& operator=(BoundaryEdge&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const BoundaryEdge& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const BoundaryEdge* internal_default_instance() {
    return reinterpret_cast<const BoundaryEdge*>(
               &_BoundaryEdge_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(BoundaryEdge* other);
  friend void swap(BoundaryEdge& a, BoundaryEdge& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline BoundaryEdge* New() const final {
    return CreateMaybeMessage<BoundaryEdge>(NULL);
  }

  BoundaryEdge* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<BoundaryEdge>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const BoundaryEdge& from);
  void MergeFrom(const BoundaryEdge& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(BoundaryEdge* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef BoundaryEdge_Type Type;
  static const Type UNKNOWN =
    BoundaryEdge_Type_UNKNOWN;
  static const Type NORMAL =
    BoundaryEdge_Type_NORMAL;
  static const Type LEFT_BOUNDARY =
    BoundaryEdge_Type_LEFT_BOUNDARY;
  static const Type RIGHT_BOUNDARY =
    BoundaryEdge_Type_RIGHT_BOUNDARY;
  static inline bool Type_IsValid(int value) {
    return BoundaryEdge_Type_IsValid(value);
  }
  static const Type Type_MIN =
    BoundaryEdge_Type_Type_MIN;
  static const Type Type_MAX =
    BoundaryEdge_Type_Type_MAX;
  static const int Type_ARRAYSIZE =
    BoundaryEdge_Type_Type_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  Type_descriptor() {
    return BoundaryEdge_Type_descriptor();
  }
  static inline const ::std::string& Type_Name(Type value) {
    return BoundaryEdge_Type_Name(value);
  }
  static inline bool Type_Parse(const ::std::string& name,
      Type* value) {
    return BoundaryEdge_Type_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // optional .cvte.hdmap.Curve curve = 1;
  bool has_curve() const;
  void clear_curve();
  static const int kCurveFieldNumber = 1;
  private:
  const ::cvte::hdmap::Curve& _internal_curve() const;
  public:
  const ::cvte::hdmap::Curve& curve() const;
  ::cvte::hdmap::Curve* release_curve();
  ::cvte::hdmap::Curve* mutable_curve();
  void set_allocated_curve(::cvte::hdmap::Curve* curve);

  // optional .cvte.hdmap.BoundaryEdge.Type type = 2;
  bool has_type() const;
  void clear_type();
  static const int kTypeFieldNumber = 2;
  ::cvte::hdmap::BoundaryEdge_Type type() const;
  void set_type(::cvte::hdmap::BoundaryEdge_Type value);

  // @@protoc_insertion_point(class_scope:cvte.hdmap.BoundaryEdge)
 private:
  void set_has_curve();
  void clear_has_curve();
  void set_has_type();
  void clear_has_type();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::cvte::hdmap::Curve* curve_;
  int type_;
  friend struct ::protobuf_map_5froad_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class BoundaryPolygon : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:cvte.hdmap.BoundaryPolygon) */ {
 public:
  BoundaryPolygon();
  virtual ~BoundaryPolygon();

  BoundaryPolygon(const BoundaryPolygon& from);

  inline BoundaryPolygon& operator=(const BoundaryPolygon& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  BoundaryPolygon(BoundaryPolygon&& from) noexcept
    : BoundaryPolygon() {
    *this = ::std::move(from);
  }

  inline BoundaryPolygon& operator=(BoundaryPolygon&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const BoundaryPolygon& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const BoundaryPolygon* internal_default_instance() {
    return reinterpret_cast<const BoundaryPolygon*>(
               &_BoundaryPolygon_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(BoundaryPolygon* other);
  friend void swap(BoundaryPolygon& a, BoundaryPolygon& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline BoundaryPolygon* New() const final {
    return CreateMaybeMessage<BoundaryPolygon>(NULL);
  }

  BoundaryPolygon* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<BoundaryPolygon>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const BoundaryPolygon& from);
  void MergeFrom(const BoundaryPolygon& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(BoundaryPolygon* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .cvte.hdmap.BoundaryEdge edge = 1;
  int edge_size() const;
  void clear_edge();
  static const int kEdgeFieldNumber = 1;
  ::cvte::hdmap::BoundaryEdge* mutable_edge(int index);
  ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::BoundaryEdge >*
      mutable_edge();
  const ::cvte::hdmap::BoundaryEdge& edge(int index) const;
  ::cvte::hdmap::BoundaryEdge* add_edge();
  const ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::BoundaryEdge >&
      edge() const;

  // @@protoc_insertion_point(class_scope:cvte.hdmap.BoundaryPolygon)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::BoundaryEdge > edge_;
  friend struct ::protobuf_map_5froad_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class RoadBoundary : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:cvte.hdmap.RoadBoundary) */ {
 public:
  RoadBoundary();
  virtual ~RoadBoundary();

  RoadBoundary(const RoadBoundary& from);

  inline RoadBoundary& operator=(const RoadBoundary& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  RoadBoundary(RoadBoundary&& from) noexcept
    : RoadBoundary() {
    *this = ::std::move(from);
  }

  inline RoadBoundary& operator=(RoadBoundary&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const RoadBoundary& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const RoadBoundary* internal_default_instance() {
    return reinterpret_cast<const RoadBoundary*>(
               &_RoadBoundary_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(RoadBoundary* other);
  friend void swap(RoadBoundary& a, RoadBoundary& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline RoadBoundary* New() const final {
    return CreateMaybeMessage<RoadBoundary>(NULL);
  }

  RoadBoundary* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<RoadBoundary>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const RoadBoundary& from);
  void MergeFrom(const RoadBoundary& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RoadBoundary* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .cvte.hdmap.BoundaryPolygon hole = 2;
  int hole_size() const;
  void clear_hole();
  static const int kHoleFieldNumber = 2;
  ::cvte::hdmap::BoundaryPolygon* mutable_hole(int index);
  ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::BoundaryPolygon >*
      mutable_hole();
  const ::cvte::hdmap::BoundaryPolygon& hole(int index) const;
  ::cvte::hdmap::BoundaryPolygon* add_hole();
  const ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::BoundaryPolygon >&
      hole() const;

  // optional .cvte.hdmap.BoundaryPolygon outer_polygon = 1;
  bool has_outer_polygon() const;
  void clear_outer_polygon();
  static const int kOuterPolygonFieldNumber = 1;
  private:
  const ::cvte::hdmap::BoundaryPolygon& _internal_outer_polygon() const;
  public:
  const ::cvte::hdmap::BoundaryPolygon& outer_polygon() const;
  ::cvte::hdmap::BoundaryPolygon* release_outer_polygon();
  ::cvte::hdmap::BoundaryPolygon* mutable_outer_polygon();
  void set_allocated_outer_polygon(::cvte::hdmap::BoundaryPolygon* outer_polygon);

  // @@protoc_insertion_point(class_scope:cvte.hdmap.RoadBoundary)
 private:
  void set_has_outer_polygon();
  void clear_has_outer_polygon();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::BoundaryPolygon > hole_;
  ::cvte::hdmap::BoundaryPolygon* outer_polygon_;
  friend struct ::protobuf_map_5froad_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class RoadROIBoundary : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:cvte.hdmap.RoadROIBoundary) */ {
 public:
  RoadROIBoundary();
  virtual ~RoadROIBoundary();

  RoadROIBoundary(const RoadROIBoundary& from);

  inline RoadROIBoundary& operator=(const RoadROIBoundary& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  RoadROIBoundary(RoadROIBoundary&& from) noexcept
    : RoadROIBoundary() {
    *this = ::std::move(from);
  }

  inline RoadROIBoundary& operator=(RoadROIBoundary&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const RoadROIBoundary& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const RoadROIBoundary* internal_default_instance() {
    return reinterpret_cast<const RoadROIBoundary*>(
               &_RoadROIBoundary_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  void Swap(RoadROIBoundary* other);
  friend void swap(RoadROIBoundary& a, RoadROIBoundary& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline RoadROIBoundary* New() const final {
    return CreateMaybeMessage<RoadROIBoundary>(NULL);
  }

  RoadROIBoundary* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<RoadROIBoundary>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const RoadROIBoundary& from);
  void MergeFrom(const RoadROIBoundary& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RoadROIBoundary* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .cvte.hdmap.RoadBoundary road_boundaries = 2;
  int road_boundaries_size() const;
  void clear_road_boundaries();
  static const int kRoadBoundariesFieldNumber = 2;
  ::cvte::hdmap::RoadBoundary* mutable_road_boundaries(int index);
  ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::RoadBoundary >*
      mutable_road_boundaries();
  const ::cvte::hdmap::RoadBoundary& road_boundaries(int index) const;
  ::cvte::hdmap::RoadBoundary* add_road_boundaries();
  const ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::RoadBoundary >&
      road_boundaries() const;

  // optional .cvte.hdmap.Id id = 1;
  bool has_id() const;
  void clear_id();
  static const int kIdFieldNumber = 1;
  private:
  const ::cvte::hdmap::Id& _internal_id() const;
  public:
  const ::cvte::hdmap::Id& id() const;
  ::cvte::hdmap::Id* release_id();
  ::cvte::hdmap::Id* mutable_id();
  void set_allocated_id(::cvte::hdmap::Id* id);

  // @@protoc_insertion_point(class_scope:cvte.hdmap.RoadROIBoundary)
 private:
  void set_has_id();
  void clear_has_id();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::RoadBoundary > road_boundaries_;
  ::cvte::hdmap::Id* id_;
  friend struct ::protobuf_map_5froad_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class RoadSection : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:cvte.hdmap.RoadSection) */ {
 public:
  RoadSection();
  virtual ~RoadSection();

  RoadSection(const RoadSection& from);

  inline RoadSection& operator=(const RoadSection& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  RoadSection(RoadSection&& from) noexcept
    : RoadSection() {
    *this = ::std::move(from);
  }

  inline RoadSection& operator=(RoadSection&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const RoadSection& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const RoadSection* internal_default_instance() {
    return reinterpret_cast<const RoadSection*>(
               &_RoadSection_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  void Swap(RoadSection* other);
  friend void swap(RoadSection& a, RoadSection& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline RoadSection* New() const final {
    return CreateMaybeMessage<RoadSection>(NULL);
  }

  RoadSection* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<RoadSection>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const RoadSection& from);
  void MergeFrom(const RoadSection& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RoadSection* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .cvte.hdmap.Id lane_id = 2;
  int lane_id_size() const;
  void clear_lane_id();
  static const int kLaneIdFieldNumber = 2;
  ::cvte::hdmap::Id* mutable_lane_id(int index);
  ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::Id >*
      mutable_lane_id();
  const ::cvte::hdmap::Id& lane_id(int index) const;
  ::cvte::hdmap::Id* add_lane_id();
  const ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::Id >&
      lane_id() const;

  // optional .cvte.hdmap.Id id = 1;
  bool has_id() const;
  void clear_id();
  static const int kIdFieldNumber = 1;
  private:
  const ::cvte::hdmap::Id& _internal_id() const;
  public:
  const ::cvte::hdmap::Id& id() const;
  ::cvte::hdmap::Id* release_id();
  ::cvte::hdmap::Id* mutable_id();
  void set_allocated_id(::cvte::hdmap::Id* id);

  // optional .cvte.hdmap.RoadBoundary boundary = 3;
  bool has_boundary() const;
  void clear_boundary();
  static const int kBoundaryFieldNumber = 3;
  private:
  const ::cvte::hdmap::RoadBoundary& _internal_boundary() const;
  public:
  const ::cvte::hdmap::RoadBoundary& boundary() const;
  ::cvte::hdmap::RoadBoundary* release_boundary();
  ::cvte::hdmap::RoadBoundary* mutable_boundary();
  void set_allocated_boundary(::cvte::hdmap::RoadBoundary* boundary);

  // @@protoc_insertion_point(class_scope:cvte.hdmap.RoadSection)
 private:
  void set_has_id();
  void clear_has_id();
  void set_has_boundary();
  void clear_has_boundary();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::Id > lane_id_;
  ::cvte::hdmap::Id* id_;
  ::cvte::hdmap::RoadBoundary* boundary_;
  friend struct ::protobuf_map_5froad_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Road : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:cvte.hdmap.Road) */ {
 public:
  Road();
  virtual ~Road();

  Road(const Road& from);

  inline Road& operator=(const Road& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Road(Road&& from) noexcept
    : Road() {
    *this = ::std::move(from);
  }

  inline Road& operator=(Road&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Road& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Road* internal_default_instance() {
    return reinterpret_cast<const Road*>(
               &_Road_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  void Swap(Road* other);
  friend void swap(Road& a, Road& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Road* New() const final {
    return CreateMaybeMessage<Road>(NULL);
  }

  Road* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Road>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Road& from);
  void MergeFrom(const Road& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Road* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef Road_Type Type;
  static const Type UNKNOWN =
    Road_Type_UNKNOWN;
  static const Type HIGHWAY =
    Road_Type_HIGHWAY;
  static const Type CITY_ROAD =
    Road_Type_CITY_ROAD;
  static const Type PARK =
    Road_Type_PARK;
  static inline bool Type_IsValid(int value) {
    return Road_Type_IsValid(value);
  }
  static const Type Type_MIN =
    Road_Type_Type_MIN;
  static const Type Type_MAX =
    Road_Type_Type_MAX;
  static const int Type_ARRAYSIZE =
    Road_Type_Type_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  Type_descriptor() {
    return Road_Type_descriptor();
  }
  static inline const ::std::string& Type_Name(Type value) {
    return Road_Type_Name(value);
  }
  static inline bool Type_Parse(const ::std::string& name,
      Type* value) {
    return Road_Type_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // repeated .cvte.hdmap.RoadSection section = 2;
  int section_size() const;
  void clear_section();
  static const int kSectionFieldNumber = 2;
  ::cvte::hdmap::RoadSection* mutable_section(int index);
  ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::RoadSection >*
      mutable_section();
  const ::cvte::hdmap::RoadSection& section(int index) const;
  ::cvte::hdmap::RoadSection* add_section();
  const ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::RoadSection >&
      section() const;

  // optional .cvte.hdmap.Id id = 1;
  bool has_id() const;
  void clear_id();
  static const int kIdFieldNumber = 1;
  private:
  const ::cvte::hdmap::Id& _internal_id() const;
  public:
  const ::cvte::hdmap::Id& id() const;
  ::cvte::hdmap::Id* release_id();
  ::cvte::hdmap::Id* mutable_id();
  void set_allocated_id(::cvte::hdmap::Id* id);

  // optional .cvte.hdmap.Id junction_id = 3;
  bool has_junction_id() const;
  void clear_junction_id();
  static const int kJunctionIdFieldNumber = 3;
  private:
  const ::cvte::hdmap::Id& _internal_junction_id() const;
  public:
  const ::cvte::hdmap::Id& junction_id() const;
  ::cvte::hdmap::Id* release_junction_id();
  ::cvte::hdmap::Id* mutable_junction_id();
  void set_allocated_junction_id(::cvte::hdmap::Id* junction_id);

  // optional .cvte.hdmap.Road.Type type = 4;
  bool has_type() const;
  void clear_type();
  static const int kTypeFieldNumber = 4;
  ::cvte::hdmap::Road_Type type() const;
  void set_type(::cvte::hdmap::Road_Type value);

  // @@protoc_insertion_point(class_scope:cvte.hdmap.Road)
 private:
  void set_has_id();
  void clear_has_id();
  void set_has_junction_id();
  void clear_has_junction_id();
  void set_has_type();
  void clear_has_type();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::RoadSection > section_;
  ::cvte::hdmap::Id* id_;
  ::cvte::hdmap::Id* junction_id_;
  int type_;
  friend struct ::protobuf_map_5froad_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// BoundaryEdge

// optional .cvte.hdmap.Curve curve = 1;
inline bool BoundaryEdge::has_curve() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void BoundaryEdge::set_has_curve() {
  _has_bits_[0] |= 0x00000001u;
}
inline void BoundaryEdge::clear_has_curve() {
  _has_bits_[0] &= ~0x00000001u;
}
inline const ::cvte::hdmap::Curve& BoundaryEdge::_internal_curve() const {
  return *curve_;
}
inline const ::cvte::hdmap::Curve& BoundaryEdge::curve() const {
  const ::cvte::hdmap::Curve* p = curve_;
  // @@protoc_insertion_point(field_get:cvte.hdmap.BoundaryEdge.curve)
  return p != NULL ? *p : *reinterpret_cast<const ::cvte::hdmap::Curve*>(
      &::cvte::hdmap::_Curve_default_instance_);
}
inline ::cvte::hdmap::Curve* BoundaryEdge::release_curve() {
  // @@protoc_insertion_point(field_release:cvte.hdmap.BoundaryEdge.curve)
  clear_has_curve();
  ::cvte::hdmap::Curve* temp = curve_;
  curve_ = NULL;
  return temp;
}
inline ::cvte::hdmap::Curve* BoundaryEdge::mutable_curve() {
  set_has_curve();
  if (curve_ == NULL) {
    auto* p = CreateMaybeMessage<::cvte::hdmap::Curve>(GetArenaNoVirtual());
    curve_ = p;
  }
  // @@protoc_insertion_point(field_mutable:cvte.hdmap.BoundaryEdge.curve)
  return curve_;
}
inline void BoundaryEdge::set_allocated_curve(::cvte::hdmap::Curve* curve) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(curve_);
  }
  if (curve) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      curve = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, curve, submessage_arena);
    }
    set_has_curve();
  } else {
    clear_has_curve();
  }
  curve_ = curve;
  // @@protoc_insertion_point(field_set_allocated:cvte.hdmap.BoundaryEdge.curve)
}

// optional .cvte.hdmap.BoundaryEdge.Type type = 2;
inline bool BoundaryEdge::has_type() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void BoundaryEdge::set_has_type() {
  _has_bits_[0] |= 0x00000002u;
}
inline void BoundaryEdge::clear_has_type() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void BoundaryEdge::clear_type() {
  type_ = 0;
  clear_has_type();
}
inline ::cvte::hdmap::BoundaryEdge_Type BoundaryEdge::type() const {
  // @@protoc_insertion_point(field_get:cvte.hdmap.BoundaryEdge.type)
  return static_cast< ::cvte::hdmap::BoundaryEdge_Type >(type_);
}
inline void BoundaryEdge::set_type(::cvte::hdmap::BoundaryEdge_Type value) {
  assert(::cvte::hdmap::BoundaryEdge_Type_IsValid(value));
  set_has_type();
  type_ = value;
  // @@protoc_insertion_point(field_set:cvte.hdmap.BoundaryEdge.type)
}

// -------------------------------------------------------------------

// BoundaryPolygon

// repeated .cvte.hdmap.BoundaryEdge edge = 1;
inline int BoundaryPolygon::edge_size() const {
  return edge_.size();
}
inline void BoundaryPolygon::clear_edge() {
  edge_.Clear();
}
inline ::cvte::hdmap::BoundaryEdge* BoundaryPolygon::mutable_edge(int index) {
  // @@protoc_insertion_point(field_mutable:cvte.hdmap.BoundaryPolygon.edge)
  return edge_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::BoundaryEdge >*
BoundaryPolygon::mutable_edge() {
  // @@protoc_insertion_point(field_mutable_list:cvte.hdmap.BoundaryPolygon.edge)
  return &edge_;
}
inline const ::cvte::hdmap::BoundaryEdge& BoundaryPolygon::edge(int index) const {
  // @@protoc_insertion_point(field_get:cvte.hdmap.BoundaryPolygon.edge)
  return edge_.Get(index);
}
inline ::cvte::hdmap::BoundaryEdge* BoundaryPolygon::add_edge() {
  // @@protoc_insertion_point(field_add:cvte.hdmap.BoundaryPolygon.edge)
  return edge_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::BoundaryEdge >&
BoundaryPolygon::edge() const {
  // @@protoc_insertion_point(field_list:cvte.hdmap.BoundaryPolygon.edge)
  return edge_;
}

// -------------------------------------------------------------------

// RoadBoundary

// optional .cvte.hdmap.BoundaryPolygon outer_polygon = 1;
inline bool RoadBoundary::has_outer_polygon() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void RoadBoundary::set_has_outer_polygon() {
  _has_bits_[0] |= 0x00000001u;
}
inline void RoadBoundary::clear_has_outer_polygon() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void RoadBoundary::clear_outer_polygon() {
  if (outer_polygon_ != NULL) outer_polygon_->Clear();
  clear_has_outer_polygon();
}
inline const ::cvte::hdmap::BoundaryPolygon& RoadBoundary::_internal_outer_polygon() const {
  return *outer_polygon_;
}
inline const ::cvte::hdmap::BoundaryPolygon& RoadBoundary::outer_polygon() const {
  const ::cvte::hdmap::BoundaryPolygon* p = outer_polygon_;
  // @@protoc_insertion_point(field_get:cvte.hdmap.RoadBoundary.outer_polygon)
  return p != NULL ? *p : *reinterpret_cast<const ::cvte::hdmap::BoundaryPolygon*>(
      &::cvte::hdmap::_BoundaryPolygon_default_instance_);
}
inline ::cvte::hdmap::BoundaryPolygon* RoadBoundary::release_outer_polygon() {
  // @@protoc_insertion_point(field_release:cvte.hdmap.RoadBoundary.outer_polygon)
  clear_has_outer_polygon();
  ::cvte::hdmap::BoundaryPolygon* temp = outer_polygon_;
  outer_polygon_ = NULL;
  return temp;
}
inline ::cvte::hdmap::BoundaryPolygon* RoadBoundary::mutable_outer_polygon() {
  set_has_outer_polygon();
  if (outer_polygon_ == NULL) {
    auto* p = CreateMaybeMessage<::cvte::hdmap::BoundaryPolygon>(GetArenaNoVirtual());
    outer_polygon_ = p;
  }
  // @@protoc_insertion_point(field_mutable:cvte.hdmap.RoadBoundary.outer_polygon)
  return outer_polygon_;
}
inline void RoadBoundary::set_allocated_outer_polygon(::cvte::hdmap::BoundaryPolygon* outer_polygon) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete outer_polygon_;
  }
  if (outer_polygon) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      outer_polygon = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, outer_polygon, submessage_arena);
    }
    set_has_outer_polygon();
  } else {
    clear_has_outer_polygon();
  }
  outer_polygon_ = outer_polygon;
  // @@protoc_insertion_point(field_set_allocated:cvte.hdmap.RoadBoundary.outer_polygon)
}

// repeated .cvte.hdmap.BoundaryPolygon hole = 2;
inline int RoadBoundary::hole_size() const {
  return hole_.size();
}
inline void RoadBoundary::clear_hole() {
  hole_.Clear();
}
inline ::cvte::hdmap::BoundaryPolygon* RoadBoundary::mutable_hole(int index) {
  // @@protoc_insertion_point(field_mutable:cvte.hdmap.RoadBoundary.hole)
  return hole_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::BoundaryPolygon >*
RoadBoundary::mutable_hole() {
  // @@protoc_insertion_point(field_mutable_list:cvte.hdmap.RoadBoundary.hole)
  return &hole_;
}
inline const ::cvte::hdmap::BoundaryPolygon& RoadBoundary::hole(int index) const {
  // @@protoc_insertion_point(field_get:cvte.hdmap.RoadBoundary.hole)
  return hole_.Get(index);
}
inline ::cvte::hdmap::BoundaryPolygon* RoadBoundary::add_hole() {
  // @@protoc_insertion_point(field_add:cvte.hdmap.RoadBoundary.hole)
  return hole_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::BoundaryPolygon >&
RoadBoundary::hole() const {
  // @@protoc_insertion_point(field_list:cvte.hdmap.RoadBoundary.hole)
  return hole_;
}

// -------------------------------------------------------------------

// RoadROIBoundary

// optional .cvte.hdmap.Id id = 1;
inline bool RoadROIBoundary::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void RoadROIBoundary::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void RoadROIBoundary::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline const ::cvte::hdmap::Id& RoadROIBoundary::_internal_id() const {
  return *id_;
}
inline const ::cvte::hdmap::Id& RoadROIBoundary::id() const {
  const ::cvte::hdmap::Id* p = id_;
  // @@protoc_insertion_point(field_get:cvte.hdmap.RoadROIBoundary.id)
  return p != NULL ? *p : *reinterpret_cast<const ::cvte::hdmap::Id*>(
      &::cvte::hdmap::_Id_default_instance_);
}
inline ::cvte::hdmap::Id* RoadROIBoundary::release_id() {
  // @@protoc_insertion_point(field_release:cvte.hdmap.RoadROIBoundary.id)
  clear_has_id();
  ::cvte::hdmap::Id* temp = id_;
  id_ = NULL;
  return temp;
}
inline ::cvte::hdmap::Id* RoadROIBoundary::mutable_id() {
  set_has_id();
  if (id_ == NULL) {
    auto* p = CreateMaybeMessage<::cvte::hdmap::Id>(GetArenaNoVirtual());
    id_ = p;
  }
  // @@protoc_insertion_point(field_mutable:cvte.hdmap.RoadROIBoundary.id)
  return id_;
}
inline void RoadROIBoundary::set_allocated_id(::cvte::hdmap::Id* id) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(id_);
  }
  if (id) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      id = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, id, submessage_arena);
    }
    set_has_id();
  } else {
    clear_has_id();
  }
  id_ = id;
  // @@protoc_insertion_point(field_set_allocated:cvte.hdmap.RoadROIBoundary.id)
}

// repeated .cvte.hdmap.RoadBoundary road_boundaries = 2;
inline int RoadROIBoundary::road_boundaries_size() const {
  return road_boundaries_.size();
}
inline void RoadROIBoundary::clear_road_boundaries() {
  road_boundaries_.Clear();
}
inline ::cvte::hdmap::RoadBoundary* RoadROIBoundary::mutable_road_boundaries(int index) {
  // @@protoc_insertion_point(field_mutable:cvte.hdmap.RoadROIBoundary.road_boundaries)
  return road_boundaries_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::RoadBoundary >*
RoadROIBoundary::mutable_road_boundaries() {
  // @@protoc_insertion_point(field_mutable_list:cvte.hdmap.RoadROIBoundary.road_boundaries)
  return &road_boundaries_;
}
inline const ::cvte::hdmap::RoadBoundary& RoadROIBoundary::road_boundaries(int index) const {
  // @@protoc_insertion_point(field_get:cvte.hdmap.RoadROIBoundary.road_boundaries)
  return road_boundaries_.Get(index);
}
inline ::cvte::hdmap::RoadBoundary* RoadROIBoundary::add_road_boundaries() {
  // @@protoc_insertion_point(field_add:cvte.hdmap.RoadROIBoundary.road_boundaries)
  return road_boundaries_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::RoadBoundary >&
RoadROIBoundary::road_boundaries() const {
  // @@protoc_insertion_point(field_list:cvte.hdmap.RoadROIBoundary.road_boundaries)
  return road_boundaries_;
}

// -------------------------------------------------------------------

// RoadSection

// optional .cvte.hdmap.Id id = 1;
inline bool RoadSection::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void RoadSection::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void RoadSection::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline const ::cvte::hdmap::Id& RoadSection::_internal_id() const {
  return *id_;
}
inline const ::cvte::hdmap::Id& RoadSection::id() const {
  const ::cvte::hdmap::Id* p = id_;
  // @@protoc_insertion_point(field_get:cvte.hdmap.RoadSection.id)
  return p != NULL ? *p : *reinterpret_cast<const ::cvte::hdmap::Id*>(
      &::cvte::hdmap::_Id_default_instance_);
}
inline ::cvte::hdmap::Id* RoadSection::release_id() {
  // @@protoc_insertion_point(field_release:cvte.hdmap.RoadSection.id)
  clear_has_id();
  ::cvte::hdmap::Id* temp = id_;
  id_ = NULL;
  return temp;
}
inline ::cvte::hdmap::Id* RoadSection::mutable_id() {
  set_has_id();
  if (id_ == NULL) {
    auto* p = CreateMaybeMessage<::cvte::hdmap::Id>(GetArenaNoVirtual());
    id_ = p;
  }
  // @@protoc_insertion_point(field_mutable:cvte.hdmap.RoadSection.id)
  return id_;
}
inline void RoadSection::set_allocated_id(::cvte::hdmap::Id* id) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(id_);
  }
  if (id) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      id = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, id, submessage_arena);
    }
    set_has_id();
  } else {
    clear_has_id();
  }
  id_ = id;
  // @@protoc_insertion_point(field_set_allocated:cvte.hdmap.RoadSection.id)
}

// repeated .cvte.hdmap.Id lane_id = 2;
inline int RoadSection::lane_id_size() const {
  return lane_id_.size();
}
inline ::cvte::hdmap::Id* RoadSection::mutable_lane_id(int index) {
  // @@protoc_insertion_point(field_mutable:cvte.hdmap.RoadSection.lane_id)
  return lane_id_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::Id >*
RoadSection::mutable_lane_id() {
  // @@protoc_insertion_point(field_mutable_list:cvte.hdmap.RoadSection.lane_id)
  return &lane_id_;
}
inline const ::cvte::hdmap::Id& RoadSection::lane_id(int index) const {
  // @@protoc_insertion_point(field_get:cvte.hdmap.RoadSection.lane_id)
  return lane_id_.Get(index);
}
inline ::cvte::hdmap::Id* RoadSection::add_lane_id() {
  // @@protoc_insertion_point(field_add:cvte.hdmap.RoadSection.lane_id)
  return lane_id_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::Id >&
RoadSection::lane_id() const {
  // @@protoc_insertion_point(field_list:cvte.hdmap.RoadSection.lane_id)
  return lane_id_;
}

// optional .cvte.hdmap.RoadBoundary boundary = 3;
inline bool RoadSection::has_boundary() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void RoadSection::set_has_boundary() {
  _has_bits_[0] |= 0x00000002u;
}
inline void RoadSection::clear_has_boundary() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void RoadSection::clear_boundary() {
  if (boundary_ != NULL) boundary_->Clear();
  clear_has_boundary();
}
inline const ::cvte::hdmap::RoadBoundary& RoadSection::_internal_boundary() const {
  return *boundary_;
}
inline const ::cvte::hdmap::RoadBoundary& RoadSection::boundary() const {
  const ::cvte::hdmap::RoadBoundary* p = boundary_;
  // @@protoc_insertion_point(field_get:cvte.hdmap.RoadSection.boundary)
  return p != NULL ? *p : *reinterpret_cast<const ::cvte::hdmap::RoadBoundary*>(
      &::cvte::hdmap::_RoadBoundary_default_instance_);
}
inline ::cvte::hdmap::RoadBoundary* RoadSection::release_boundary() {
  // @@protoc_insertion_point(field_release:cvte.hdmap.RoadSection.boundary)
  clear_has_boundary();
  ::cvte::hdmap::RoadBoundary* temp = boundary_;
  boundary_ = NULL;
  return temp;
}
inline ::cvte::hdmap::RoadBoundary* RoadSection::mutable_boundary() {
  set_has_boundary();
  if (boundary_ == NULL) {
    auto* p = CreateMaybeMessage<::cvte::hdmap::RoadBoundary>(GetArenaNoVirtual());
    boundary_ = p;
  }
  // @@protoc_insertion_point(field_mutable:cvte.hdmap.RoadSection.boundary)
  return boundary_;
}
inline void RoadSection::set_allocated_boundary(::cvte::hdmap::RoadBoundary* boundary) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete boundary_;
  }
  if (boundary) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      boundary = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, boundary, submessage_arena);
    }
    set_has_boundary();
  } else {
    clear_has_boundary();
  }
  boundary_ = boundary;
  // @@protoc_insertion_point(field_set_allocated:cvte.hdmap.RoadSection.boundary)
}

// -------------------------------------------------------------------

// Road

// optional .cvte.hdmap.Id id = 1;
inline bool Road::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Road::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Road::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline const ::cvte::hdmap::Id& Road::_internal_id() const {
  return *id_;
}
inline const ::cvte::hdmap::Id& Road::id() const {
  const ::cvte::hdmap::Id* p = id_;
  // @@protoc_insertion_point(field_get:cvte.hdmap.Road.id)
  return p != NULL ? *p : *reinterpret_cast<const ::cvte::hdmap::Id*>(
      &::cvte::hdmap::_Id_default_instance_);
}
inline ::cvte::hdmap::Id* Road::release_id() {
  // @@protoc_insertion_point(field_release:cvte.hdmap.Road.id)
  clear_has_id();
  ::cvte::hdmap::Id* temp = id_;
  id_ = NULL;
  return temp;
}
inline ::cvte::hdmap::Id* Road::mutable_id() {
  set_has_id();
  if (id_ == NULL) {
    auto* p = CreateMaybeMessage<::cvte::hdmap::Id>(GetArenaNoVirtual());
    id_ = p;
  }
  // @@protoc_insertion_point(field_mutable:cvte.hdmap.Road.id)
  return id_;
}
inline void Road::set_allocated_id(::cvte::hdmap::Id* id) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(id_);
  }
  if (id) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      id = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, id, submessage_arena);
    }
    set_has_id();
  } else {
    clear_has_id();
  }
  id_ = id;
  // @@protoc_insertion_point(field_set_allocated:cvte.hdmap.Road.id)
}

// repeated .cvte.hdmap.RoadSection section = 2;
inline int Road::section_size() const {
  return section_.size();
}
inline void Road::clear_section() {
  section_.Clear();
}
inline ::cvte::hdmap::RoadSection* Road::mutable_section(int index) {
  // @@protoc_insertion_point(field_mutable:cvte.hdmap.Road.section)
  return section_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::RoadSection >*
Road::mutable_section() {
  // @@protoc_insertion_point(field_mutable_list:cvte.hdmap.Road.section)
  return &section_;
}
inline const ::cvte::hdmap::RoadSection& Road::section(int index) const {
  // @@protoc_insertion_point(field_get:cvte.hdmap.Road.section)
  return section_.Get(index);
}
inline ::cvte::hdmap::RoadSection* Road::add_section() {
  // @@protoc_insertion_point(field_add:cvte.hdmap.Road.section)
  return section_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::cvte::hdmap::RoadSection >&
Road::section() const {
  // @@protoc_insertion_point(field_list:cvte.hdmap.Road.section)
  return section_;
}

// optional .cvte.hdmap.Id junction_id = 3;
inline bool Road::has_junction_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Road::set_has_junction_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Road::clear_has_junction_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline const ::cvte::hdmap::Id& Road::_internal_junction_id() const {
  return *junction_id_;
}
inline const ::cvte::hdmap::Id& Road::junction_id() const {
  const ::cvte::hdmap::Id* p = junction_id_;
  // @@protoc_insertion_point(field_get:cvte.hdmap.Road.junction_id)
  return p != NULL ? *p : *reinterpret_cast<const ::cvte::hdmap::Id*>(
      &::cvte::hdmap::_Id_default_instance_);
}
inline ::cvte::hdmap::Id* Road::release_junction_id() {
  // @@protoc_insertion_point(field_release:cvte.hdmap.Road.junction_id)
  clear_has_junction_id();
  ::cvte::hdmap::Id* temp = junction_id_;
  junction_id_ = NULL;
  return temp;
}
inline ::cvte::hdmap::Id* Road::mutable_junction_id() {
  set_has_junction_id();
  if (junction_id_ == NULL) {
    auto* p = CreateMaybeMessage<::cvte::hdmap::Id>(GetArenaNoVirtual());
    junction_id_ = p;
  }
  // @@protoc_insertion_point(field_mutable:cvte.hdmap.Road.junction_id)
  return junction_id_;
}
inline void Road::set_allocated_junction_id(::cvte::hdmap::Id* junction_id) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(junction_id_);
  }
  if (junction_id) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      junction_id = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, junction_id, submessage_arena);
    }
    set_has_junction_id();
  } else {
    clear_has_junction_id();
  }
  junction_id_ = junction_id;
  // @@protoc_insertion_point(field_set_allocated:cvte.hdmap.Road.junction_id)
}

// optional .cvte.hdmap.Road.Type type = 4;
inline bool Road::has_type() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Road::set_has_type() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Road::clear_has_type() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Road::clear_type() {
  type_ = 0;
  clear_has_type();
}
inline ::cvte::hdmap::Road_Type Road::type() const {
  // @@protoc_insertion_point(field_get:cvte.hdmap.Road.type)
  return static_cast< ::cvte::hdmap::Road_Type >(type_);
}
inline void Road::set_type(::cvte::hdmap::Road_Type value) {
  assert(::cvte::hdmap::Road_Type_IsValid(value));
  set_has_type();
  type_ = value;
  // @@protoc_insertion_point(field_set:cvte.hdmap.Road.type)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace hdmap
}  // namespace cvte

namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::cvte::hdmap::BoundaryEdge_Type> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::cvte::hdmap::BoundaryEdge_Type>() {
  return ::cvte::hdmap::BoundaryEdge_Type_descriptor();
}
template <> struct is_proto_enum< ::cvte::hdmap::Road_Type> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::cvte::hdmap::Road_Type>() {
  return ::cvte::hdmap::Road_Type_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_map_5froad_2eproto
